#ifndef __IPCM_LINUX_H__
#define __IPCM_LINUX_H__

typedef enum _IPCM_BASE_CMD_E {
	IPCM_BASE_FLUSH_DATA,
	IPCM_BASE_INV_DATA,
	//get pool addr/size , freertos addr/size
	IPCM_BASE_GET_POOL_ADDR,
	IPCM_BASE_GET_RTOS_ADDR,
	IPCM_BASE_GET_LOG_ADDR,
	IPCM_BASE_LOCK,
	IPCM_BASE_UNLOCK,

	IPCM_BASE_CMD_BUTT,
} IPCM_BASE_CMD_E;

typedef enum _IPCM_SYS_CMD_E {
	IPCM_SYS_GET_SYSINFO,
	IPCM_SYS_GET_LOG,

	IPCM_SYS_CMD_BUTT,
} IPCM_SYS_CMD_E;

typedef enum _IPCM_CUST_CMD_E {
	IPCM_CUST_GET_POOL_OFFSET,
	IPCM_CUST_GET_DATA,
	IPCM_CUST_RLS_DATA,
	IPCM_CUST_POOL_RESET,

	IPCM_CUST_CMD_BUTT,
} IPCM_CUST_CMD_E;

typedef struct _IPCM_PADDR_INFO_S {
	unsigned int paddr;
	unsigned int size;
} IPCM_PADDR_INFO_S;

#define IPCM_IOC_MAGIC		'I'
#define IPCM_IOC_BASE		0x20
#define IPCM_IOC_MSG		0x40
#define IPCM_IOC_SYS		0x80
#define IPCM_IOC_CUST		0xD0

#define IPCM_IOC_FLUSH_DATA		_IOW(IPCM_IOC_MAGIC, IPCM_IOC_BASE + IPCM_BASE_FLUSH_DATA, IPCM_FLUSH_PARAM)
#define IPCM_IOC_INV_DATA		_IOW(IPCM_IOC_MAGIC, IPCM_IOC_BASE + IPCM_BASE_INV_DATA, IPCM_FLUSH_PARAM)
#define IPCM_IOC_GET_POOL_ADDR	_IOR(IPCM_IOC_MAGIC, IPCM_IOC_BASE + IPCM_BASE_GET_POOL_ADDR, IPCM_PADDR_INFO_S)
#define IPCM_IOC_GET_RTOS_ADDR	_IOR(IPCM_IOC_MAGIC, IPCM_IOC_BASE + IPCM_BASE_GET_RTOS_ADDR, IPCM_PADDR_INFO_S)
#define IPCM_IOC_GET_LOG_ADDR	_IOR(IPCM_IOC_MAGIC, IPCM_IOC_BASE + IPCM_BASE_GET_LOG_ADDR, IPCM_PADDR_INFO_S)
#define IPCM_IOC_LOCK			_IO(IPCM_IOC_MAGIC, IPCM_IOC_MSG + IPCM_BASE_LOCK)
#define IPCM_IOC_UNLOCK			_IO(IPCM_IOC_MAGIC, IPCM_IOC_MSG + IPCM_BASE_UNLOCK)

#define IPCM_IOC_MSG_POOL_RESET		_IO(IPCM_IOC_MAGIC, IPCM_IOC_MSG + IPCM_MSG_POOL_RESET)
#define IPCM_IOC_CUST_GET_POOL_OFF  _IOR(IPCM_IOC_MAGIC, IPCM_IOC_CUST + IPCM_CUST_GET_POOL_OFFSET, unsigned int)
#define IPCM_IOC_CUST_GET_DATA		_IO(IPCM_IOC_MAGIC, IPCM_IOC_CUST + IPCM_CUST_GET_DATA)
#define IPCM_IOC_CUST_RLS_DATA		_IO(IPCM_IOC_MAGIC, IPCM_IOC_CUST + IPCM_CUST_RLS_DATA)
#define IPCM_IOC_CUST_POOL_RESET		_IO(IPCM_IOC_MAGIC, IPCM_IOC_CUST + IPCM_CUST_POOL_RESET)

#define IPCM_IOC_GET_SYSINFO	_IOR(IPCM_IOC_MAGIC, IPCM_IOC_SYS + IPCM_SYS_GET_SYSINFO, MsgData)
#define IPCM_IOC_GET_LOG		_IOR(IPCM_IOC_MAGIC, IPCM_IOC_SYS + IPCM_SYS_GET_LOG, MsgData)

#endif
