#ifndef _GFBG_REG_H_
#define _GFBG_REG_H_

#define REG_DISP_BASE(x) (reg_disp_base[x])
#define REG_DSI_MAC_BASE(x) (reg_dsi_mac_base[x])
#define REG_DSI_WRAP_BASE(x) (reg_dsi_wrap_base[x])
#define REG_VO_MAC_BASE(x) (reg_vo_mac_base[x])
#define REG_VO_SYS_OENC_BASE(x) (reg_oenc_base[x])

// #define REG_DISP_BASE(x) (0x0A094000)
// #define REG_DSI_MAC_BASE(x) (0x0A099000)
// #define REG_DSI_WRAP_BASE(x) (0x0A098000)
// #define REG_VO_MAC_BASE(x) (0x0A0A8000)
// #define REG_VO_SYS_OENC_BASE(x) (0x0A0AA000)

//GOP
#define REG_DISP_GOP_BASE(x) (REG_DISP_BASE(x))
#define REG_GOP_OFFSET(x) (0xc00 + 0x200*x)


// ============== VO MAC ============== //
// bt interface
#define REG_VO_MAC_BT_CFG(x) (REG_VO_MAC_BASE(x) + 0x10)
#define REG_VO_MAC_BT_ENC(x) (REG_VO_MAC_BASE(x) + 0x14)
#define REG_VO_MAC_BT_SYNC_CODE(x) (REG_VO_MAC_BASE(x) + 0x18)
#define REG_VO_MAC_BT_BLK_DATA(x) (REG_VO_MAC_BASE(x) + 0x1C)
// i80 interface
#define REG_VO_MAC_MCU_IF_CTRL(x) (REG_VO_MAC_BASE(x) + 0x20)
#define REG_VO_MAC_MCU_SW_CTRL(x) (REG_VO_MAC_BASE(x) + 0x24)
#define REG_VO_MAC_MCU_STATUS(x) (REG_VO_MAC_BASE(x) + 0x28)
#define REG_VO_MAC_MCU_INT_STATUS(x) (REG_VO_MAC_BASE(x) + 0x2c)
#define REG_VO_MAC_HW_MCU_AUTO(x) (REG_VO_MAC_BASE(x) + 0x30)
#define REG_VO_MAC_HW_MCU_CMD(x) (REG_VO_MAC_BASE(x) + 0x34)
#define REG_VO_MAC_HW_MCU_CMD0(x) (REG_VO_MAC_BASE(x) + 0x38)
#define REG_VO_MAC_HW_MCU_CMD1(x) (REG_VO_MAC_BASE(x) + 0x3C)
#define REG_VO_MAC_HW_MCU_CMD2(x) (REG_VO_MAC_BASE(x) + 0x40)
#define REG_VO_MAC_HW_MCU_CMD3(x) (REG_VO_MAC_BASE(x) + 0x44)
#define REG_VO_MAC_HW_MCU_CMD4(x) (REG_VO_MAC_BASE(x) + 0x48)
#define REG_VO_MAC_HW_MCU_CMD5(x) (REG_VO_MAC_BASE(x) + 0x4C)
#define REG_VO_MAC_HW_MCU_CMD6(x) (REG_VO_MAC_BASE(x) + 0x50)
#define REG_VO_MAC_HW_MCU_CMD7(x) (REG_VO_MAC_BASE(x) + 0x54)
#define REG_VO_MAC_HW_MCU_SW_OV(x) (REG_VO_MAC_BASE(x) + 0x58)
//Serial RGB interface
#define REG_VO_MAC_SRGB_CTRL(x) (REG_VO_MAC_BASE(x) + 0x60)
//vo mux
#define REG_VO_MAC_VO_MUX(x) (REG_VO_MAC_BASE(x) + 0x70)
#define REG_VO_MAC_VO_MUX0(x) (REG_VO_MAC_BASE(x) + 0x90)
#define REG_VO_MAC_VO_MUX1(x) (REG_VO_MAC_BASE(x) + 0x94)
#define REG_VO_MAC_VO_MUX2(x) (REG_VO_MAC_BASE(x) + 0x98)
#define REG_VO_MAC_VO_MUX3(x) (REG_VO_MAC_BASE(x) + 0x9C)
#define REG_VO_MAC_VO_MUX4(x) (REG_VO_MAC_BASE(x) + 0xA0)
#define REG_VO_MAC_VO_MUX5(x) (REG_VO_MAC_BASE(x) + 0xA4)
#define REG_VO_MAC_VO_MUX6(x) (REG_VO_MAC_BASE(x) + 0xA8)
#define REG_VO_MAC_VO_MUX7(x) (REG_VO_MAC_BASE(x) + 0xAC)
#define REG_VO_MAC_VO_MUX8(x) (REG_VO_MAC_BASE(x) + 0xB0)
#define REG_VO_MAC_VO_MUX9(x) (REG_VO_MAC_BASE(x) + 0xB4)
#define REG_VO_MAC_VO_MUXA(x) (REG_VO_MAC_BASE(x) + 0xB8)

// ============== DISP ============== //
#define REG_DISP_CFG(x) (REG_DISP_BASE(x) + 0x00)
#define REG_DISP_TOTAL(x) (REG_DISP_BASE(x) + 0x04)
#define REG_DISP_VSYNC(x) (REG_DISP_BASE(x) + 0x08)
#define REG_DISP_VFDE(x) (REG_DISP_BASE(x) + 0x0C)
#define REG_DISP_VMDE(x) (REG_DISP_BASE(x) + 0x10)
#define REG_DISP_HSYNC(x) (REG_DISP_BASE(x) + 0x14)
#define REG_DISP_HFDE(x) (REG_DISP_BASE(x) + 0x18)
#define REG_DISP_HMDE(x) (REG_DISP_BASE(x) + 0x1C)
#define REG_DISP_RD_TH_Y_MSB(x) (REG_DISP_BASE(x) + 0x2c)
#define REG_DISP_FIFO_TH(x) (REG_DISP_BASE(x) + 0x30)
#define REG_DISP_ADDR0_L(x) (REG_DISP_BASE(x) + 0x34)
#define REG_DISP_ADDR0_H(x) (REG_DISP_BASE(x) + 0x38)
#define REG_DISP_ADDR1_L(x) (REG_DISP_BASE(x) + 0x3C)
#define REG_DISP_ADDR1_H(x) (REG_DISP_BASE(x) + 0x40)
#define REG_DISP_ADDR2_L(x) (REG_DISP_BASE(x) + 0x44)
#define REG_DISP_ADDR2_H(x) (REG_DISP_BASE(x) + 0x48)
#define REG_DISP_PITCH_Y(x) (REG_DISP_BASE(x) + 0x4C)
#define REG_DISP_PITCH_C(x) (REG_DISP_BASE(x) + 0x50)
#define REG_DISP_OFFSET(x) (REG_DISP_BASE(x) + 0x54)
#define REG_DISP_SIZE(x) (REG_DISP_BASE(x) + 0x58)
#define REG_DISP_OUT_CSC0(x) (REG_DISP_BASE(x) + 0x5C)
#define REG_DISP_OUT_CSC1(x) (REG_DISP_BASE(x) + 0x60)
#define REG_DISP_OUT_CSC2(x) (REG_DISP_BASE(x) + 0x64)
#define REG_DISP_OUT_CSC3(x) (REG_DISP_BASE(x) + 0x68)
#define REG_DISP_OUT_CSC4(x) (REG_DISP_BASE(x) + 0x6C)
#define REG_DISP_OUT_CSC_SUB(x) (REG_DISP_BASE(x) + 0x70)
#define REG_DISP_OUT_CSC_ADD(x) (REG_DISP_BASE(x) + 0x74)
#define REG_DISP_IN_CSC0(x) (REG_DISP_BASE(x) + 0x78)
#define REG_DISP_IN_CSC1(x) (REG_DISP_BASE(x) + 0x7C)
#define REG_DISP_IN_CSC2(x) (REG_DISP_BASE(x) + 0x80)
#define REG_DISP_IN_CSC3(x) (REG_DISP_BASE(x) + 0x84)
#define REG_DISP_IN_CSC4(x) (REG_DISP_BASE(x) + 0x88)
#define REG_DISP_IN_CSC_SUB(x) (REG_DISP_BASE(x) + 0x8C)
#define REG_DISP_IN_CSC_ADD(x) (REG_DISP_BASE(x) + 0x90)
#define REG_DISP_PAT_CFG(x) (REG_DISP_BASE(x) + 0x94)
#define REG_DISP_PAT_COLOR0(x) (REG_DISP_BASE(x) + 0x98)
#define REG_DISP_PAT_COLOR1(x) (REG_DISP_BASE(x) + 0x9C)
#define REG_DISP_PAT_COLOR2(x) (REG_DISP_BASE(x) + 0xA0)
#define REG_DISP_PAT_COLOR3(x) (REG_DISP_BASE(x) + 0xA4)
#define REG_DISP_PAT_COLOR4(x) (REG_DISP_BASE(x) + 0xA8)
#define REG_DISP_DBG(x) (REG_DISP_BASE(x) + 0xAC)
#define REG_DISP_AXI_ST(x) (REG_DISP_BASE(x) + 0xB0)
#define REG_DISP_CATCH(x) (REG_DISP_BASE(x) + 0xC0)
#define REG_DISP_CHECKSUM0(x) (REG_DISP_BASE(x) + 0xC4)
#define REG_DISP_CHECKSUM1(x) (REG_DISP_BASE(x) + 0xC8)
#define REG_DISP_CHECKSUM2(x) (REG_DISP_BASE(x) + 0xCC)
#define REG_DISP_DUMMY0(x) (REG_DISP_BASE(x) + 0xF8)
#define REG_DISP_DUMMY1(x) (REG_DISP_BASE(x) + 0xFC)
#define REG_DISP_LINE_BUFFER_SERIAL(x) (REG_DISP_BASE(x) + 0x3A4)

// INT
#define REG_DISP_DEBUG_STATUS(x) (REG_DISP_BASE(x) + 0x370)
#define REG_DISP_INT_SEL(x) (REG_DISP_BASE(x) + 0x374)
#define REG_DISP_INT_CLR(x) (REG_DISP_BASE(x) + 0x378)

// GAMMA
#define REG_DISP_GAMMA_CTRL(x) (REG_DISP_BASE(x) + 0x180)
#define REG_DISP_GAMMA_WR_LUT(x) (REG_DISP_BASE(x) + 0x184)
#define REG_DISP_GAMMA_RD_LUT(x) (REG_DISP_BASE(x) + 0x188)

// ============== DSI MAC============== //
#define REG_DSI_MAC_EN(x)  (REG_DSI_MAC_BASE(x) + 0x00)
#define REG_DSI_HS_0(x)    (REG_DSI_MAC_BASE(x) + 0x04)
#define REG_DSI_HS_1(x)    (REG_DSI_MAC_BASE(x) + 0x08)
#define REG_DSI_ESC(x)     (REG_DSI_MAC_BASE(x) + 0x0C)
#define REG_DSI_ESC_TX0(x) (REG_DSI_MAC_BASE(x) + 0x10)
#define REG_DSI_ESC_TX1(x) (REG_DSI_MAC_BASE(x) + 0x14)
#define REG_DSI_ESC_TX2(x) (REG_DSI_MAC_BASE(x) + 0x18)
#define REG_DSI_ESC_TX3(x) (REG_DSI_MAC_BASE(x) + 0x1C)
#define REG_DSI_ESC_RX0(x) (REG_DSI_MAC_BASE(x) + 0x20)
#define REG_DSI_ESC_RX1(x) (REG_DSI_MAC_BASE(x) + 0x24)
#define REG_LVDSTX_MAC(x) (REG_DSI_MAC_BASE(x) + 0x30)

// ============== DSI PHY ============== //
#define REG_DSI_PHY_EN(x)             (REG_DSI_WRAP_BASE(x) + 0x00)
#define REG_DSI_PHY_CLK_CFG1(x)       (REG_DSI_WRAP_BASE(x) + 0x04)
#define REG_DSI_PHY_CLK_CFG2(x)       (REG_DSI_WRAP_BASE(x) + 0x08)
#define REG_DSI_PHY_ESC_INIT(x)       (REG_DSI_WRAP_BASE(x) + 0x0C)
#define REG_DSI_PHY_ESC_WAKE(x)       (REG_DSI_WRAP_BASE(x) + 0x10)
#define REG_DSI_PHY_HS_CFG1(x)        (REG_DSI_WRAP_BASE(x) + 0x14)
#define REG_DSI_PHY_HS_CFG2(x)        (REG_DSI_WRAP_BASE(x) + 0x18)
#define REG_DSI_PHY_CAL_CFG(x)        (REG_DSI_WRAP_BASE(x) + 0x1C)
#define REG_DSI_PHY_CAL_NUM(x)        (REG_DSI_WRAP_BASE(x) + 0x20)
#define REG_DSI_PHY_CLK_STATE(x)      (REG_DSI_WRAP_BASE(x) + 0x24)
#define REG_DSI_PHY_DATA0_STATE(x)    (REG_DSI_WRAP_BASE(x) + 0x28)
#define REG_DSI_PHY_DATA12_STATE(x)   (REG_DSI_WRAP_BASE(x) + 0x2C)
#define REG_DSI_PHY_DATA3_STATE(x)    (REG_DSI_WRAP_BASE(x) + 0x30)
#define REG_DSI_PHY_HS_OV(x)          (REG_DSI_WRAP_BASE(x) + 0x38)
#define REG_DSI_PHY_HS_SW1(x)         (REG_DSI_WRAP_BASE(x) + 0x3C)
#define REG_DSI_PHY_HS_SW2(x)         (REG_DSI_WRAP_BASE(x) + 0x40)
#define REG_DSI_PHY_DATA_OV(x)        (REG_DSI_WRAP_BASE(x) + 0x44)
#define REG_DSI_PHY_LPTX_OV(x)        (REG_DSI_WRAP_BASE(x) + 0x4C)
#define REG_DSI_PHY_LPRX_OV(x)        (REG_DSI_WRAP_BASE(x) + 0x4C)
#define REG_DSI_PHY_PD_TXDRV(x)       (REG_DSI_WRAP_BASE(x) + 0x50)
#define REG_DSI_PHY_PD_EN_TX(x)       (REG_DSI_WRAP_BASE(x) + 0x54)
#define REG_DSI_PHY_EN_SUBLVDS(x)     (REG_DSI_WRAP_BASE(x) + 0x5C)
#define REG_DSI_PHY_EN_TXBIAS_OP(x)   (REG_DSI_WRAP_BASE(x) + 0x60)
#define REG_DSI_PHY_PD(x)             (REG_DSI_WRAP_BASE(x) + 0x64)
#define REG_DSI_PHY_TXPLL(x)          (REG_DSI_WRAP_BASE(x) + 0x6C)
#define REG_DSI_PHY_REG_74(x)         (REG_DSI_WRAP_BASE(x) + 0x74)
#define REG_DSI_PHY_REG_8C(x)         (REG_DSI_WRAP_BASE(x) + 0x8C)
#define REG_DSI_PHY_VSEL(x)           (REG_DSI_WRAP_BASE(x) + 0x88)
#define REG_DSI_PHY_REG_SET(x)        (REG_DSI_WRAP_BASE(x) + 0x90)
#define REG_DSI_PHY_LANE_SEL(x)       (REG_DSI_WRAP_BASE(x) + 0x9C)
#define REG_DSI_PHY_LANE_PN_SWAP(x)   (REG_DSI_WRAP_BASE(x) + 0xA0)
#define REG_DSI_PHY_LVDS_EN(x)        (REG_DSI_WRAP_BASE(x) + 0xB4)
#define REG_DSI_PHY_EXT_GPIO(x)       (REG_DSI_WRAP_BASE(x) + 0xC0)
#define REG_DSI_PHY_GPO(x)            (REG_DSI_WRAP_BASE(x) + 0xC4)
#define REG_DSI_PHY_GPI(x)            (REG_DSI_WRAP_BASE(x) + 0xC8)

// DISP GOP
//The z below represents different ow
#define REG_DISP_GOP_FMT(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x00)
#define REG_DISP_GOP_H_RANGE(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x04)
#define REG_DISP_GOP_V_RANGE(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x08)
#define REG_DISP_GOP_ADDR_L(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x0c)
#define REG_DISP_GOP_ADDR_H(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x10)
#define REG_DISP_GOP_CROP_PITCH(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x14)
#define REG_DISP_GOP_SIZE(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x20*z + 0x18)
#define REG_DISP_GOP_CFG(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x100)
#define REG_DISP_GOP_256LUT0(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x104)
#define REG_DISP_GOP_256LUT1(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x108)
#define REG_DISP_GOP_COLORKEY(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x10c)
#define REG_DISP_GOP_FONTCOLOR(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x110)
#define REG_DISP_GOP_FONTBOX_CTRL(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x120)
//The z below represents different fontbox instance
#define REG_DISP_GOP_FONTBOX_CFG(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x10*z + 0x124)
#define REG_DISP_GOP_FONTBOX_INIT(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x10*z + 0x128)
#define REG_DISP_GOP_FONTBOX_REC(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x10*z + 0x12c)
#define REG_DISP_GOP_BW_LIMIT(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x140)
#define REG_DISP_GOP_DEC_CTRL(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x150)
#define REG_DISP_GOP_DEC_DEBUG(x, y) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x154)
//The z below represents length
#define REG_DISP_GOP_16LUT(x, y, z) (REG_DISP_GOP_BASE(x) + REG_GOP_OFFSET(y) + 0x4 * (z) + 0x160)

// OSD encoder
#define REG_VO_SYS_OENC_RST(x) (REG_VO_SYS_OENC_BASE(x) + 0x00)
#define REG_VO_SYS_OENC_INT_GO(x) (REG_VO_SYS_OENC_BASE(x) + 0x04)
#define REG_VO_SYS_OENC_HEADER_CFG(x) (REG_VO_SYS_OENC_BASE(x) + 0x08)
#define REG_VO_SYS_OENC_CFG(x) (REG_VO_SYS_OENC_BASE(x) + 0x10)
#define REG_VO_SYS_OENC_RANGE(x) (REG_VO_SYS_OENC_BASE(x) + 0x14)
#define REG_VO_SYS_OENC_PITCH(x) (REG_VO_SYS_OENC_BASE(x) + 0x18)
#define REG_VO_SYS_OENC_SRC_ADDR(x) (REG_VO_SYS_OENC_BASE(x) + 0x20)
#define REG_VO_SYS_OENC_WPROT_LADDR(x) (REG_VO_SYS_OENC_BASE(x) + 0x30)
#define REG_VO_SYS_OENC_WPROT_UADDR(x) (REG_VO_SYS_OENC_BASE(x) + 0x38)
#define REG_VO_SYS_OENC_BSO_ADDR(x) (REG_VO_SYS_OENC_BASE(x) + 0x40)
#define REG_VO_SYS_OENC_LIMIT_BSZ(x) (REG_VO_SYS_OENC_BASE(x) + 0x48)
#define REG_VO_SYS_OENC_BSO_SZ(x) (REG_VO_SYS_OENC_BASE(x) + 0x4C)
#define REG_VO_SYS_OENC_WPROT_DEBUG(x) (REG_VO_SYS_OENC_BASE(x) + 0x50)

#endif  // _GFBG_REG_H_
