/*
 * Copyright (C) Cvitek Co., Ltd. 2019-2022. All rights reserved.
 *
 * File Name:reg_blocks_csi_wrap.h
 * Description:HW register description
 */

#ifndef _REG_BLOCKS_CSI_WRAP_H_
#define _REG_BLOCKS_CSI_WRAP_H_

#ifdef __cplusplus
extern "C" {
#endif

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_TOP_T {
	union REG_SENSOR_PHY_TOP_00             REG_00;
	union REG_SENSOR_PHY_TOP_04             REG_04;
	union REG_SENSOR_PHY_TOP_08             REG_08;
	uint32_t                                _resv_0xc[1];
	union REG_SENSOR_PHY_TOP_10             REG_10;
	union REG_SENSOR_PHY_TOP_14             REG_14;
	union REG_SENSOR_PHY_TOP_18             REG_18;
	union REG_SENSOR_PHY_TOP_1C             REG_1C;
	union REG_SENSOR_PHY_TOP_20             REG_20;
	union REG_SENSOR_PHY_TOP_24             REG_24;
	union REG_SENSOR_PHY_TOP_28             REG_28;
	union REG_SENSOR_PHY_TOP_2C             REG_2C;
	union REG_SENSOR_PHY_TOP_30             REG_30;
	union REG_SENSOR_PHY_TOP_34             REG_34;
	union REG_SENSOR_PHY_TOP_38             REG_38;
	union REG_SENSOR_PHY_TOP_3C             REG_3C;
	union REG_SENSOR_PHY_TOP_40             REG_40;
	union REG_SENSOR_PHY_TOP_44             REG_44;
	union REG_SENSOR_PHY_TOP_48             REG_48;
	union REG_SENSOR_PHY_TOP_4C             REG_4C;
	union REG_SENSOR_PHY_TOP_50             REG_50;
	union REG_SENSOR_PHY_TOP_54             REG_54;
	union REG_SENSOR_PHY_TOP_58             REG_58;
	union REG_SENSOR_PHY_TOP_5C             REG_5C;
	union REG_SENSOR_PHY_TOP_60             REG_60;
	union REG_SENSOR_PHY_TOP_64             REG_64;
	union REG_SENSOR_PHY_TOP_68             REG_68;
	union REG_SENSOR_PHY_TOP_6C             REG_6C;
	union REG_SENSOR_PHY_TOP_70             REG_70;
	union REG_SENSOR_PHY_TOP_74             REG_74;
	union REG_SENSOR_PHY_TOP_78             REG_78;
	union REG_SENSOR_PHY_TOP_7C             REG_7C;
	union REG_SENSOR_PHY_TOP_80             REG_80;
	union REG_SENSOR_PHY_TOP_84             REG_84;
	union REG_SENSOR_PHY_TOP_88             REG_88;
	uint32_t                                _resv_0x8c[1];
	union REG_SENSOR_PHY_TOP_90             REG_90;
	union REG_SENSOR_PHY_TOP_94             REG_94;
	union REG_SENSOR_PHY_TOP_98             REG_98;
	union REG_SENSOR_PHY_TOP_9C             REG_9C;
	union REG_SENSOR_PHY_TOP_A0             REG_A0;
	union REG_SENSOR_PHY_TOP_A4             REG_A4;
	union REG_SENSOR_PHY_TOP_A8             REG_A8;
	union REG_SENSOR_PHY_TOP_AC             REG_AC;
	union REG_SENSOR_PHY_TOP_B0             REG_B0;
	union REG_SENSOR_PHY_TOP_B4             REG_B4;
	union REG_SENSOR_PHY_TOP_B8             REG_B8;
	union REG_SENSOR_PHY_TOP_BC             REG_BC;
	union REG_SENSOR_PHY_TOP_C0             REG_C0;
	union REG_SENSOR_PHY_TOP_C4             REG_C4;
	uint32_t                                _resv_0xc8[2];
	union REG_SENSOR_PHY_TOP_D0             REG_D0;
	union REG_SENSOR_PHY_TOP_D4             REG_D4;
	union REG_SENSOR_PHY_TOP_D8             REG_D8;
	union REG_SENSOR_PHY_TOP_DC             REG_DC;
	union REG_SENSOR_PHY_TOP_E0             REG_E0;
	union REG_SENSOR_PHY_TOP_E4             REG_E4;
	union REG_SENSOR_PHY_TOP_E8             REG_E8;
	union REG_SENSOR_PHY_TOP_EC             REG_EC;
	union REG_SENSOR_PHY_TOP_F0             REG_F0;
	union REG_SENSOR_PHY_TOP_F4             REG_F4;
	union REG_SENSOR_PHY_TOP_F8             REG_F8;
	union REG_SENSOR_PHY_TOP_FC             REG_FC;
	union REG_SENSOR_PHY_TOP_100            REG_100;
	union REG_SENSOR_PHY_TOP_104            REG_104;
	union REG_SENSOR_PHY_TOP_108            REG_108;
	union REG_SENSOR_PHY_TOP_10C            REG_10C;
	union REG_SENSOR_PHY_TOP_110            REG_110;
	uint32_t                                _resv_0x114[3];
	union REG_SENSOR_PHY_TOP_120            REG_120;
	union REG_SENSOR_PHY_TOP_124            REG_124;
	union REG_SENSOR_PHY_TOP_128            REG_128;
	union REG_SENSOR_PHY_TOP_12C            REG_12C;
	union REG_SENSOR_PHY_TOP_130            REG_130;
	union REG_SENSOR_PHY_TOP_134            REG_134;
	union REG_SENSOR_PHY_TOP_138            REG_138;
	union REG_SENSOR_PHY_TOP_13C            REG_13C;
	union REG_SENSOR_PHY_TOP_140            REG_140;
	union REG_SENSOR_PHY_TOP_144            REG_144;
	union REG_SENSOR_PHY_TOP_148            REG_148;
	union REG_SENSOR_PHY_TOP_14C            REG_14C;
	union REG_SENSOR_PHY_TOP_150            REG_150;
	union REG_SENSOR_PHY_TOP_154            REG_154;
	union REG_SENSOR_PHY_TOP_158            REG_158;
	union REG_SENSOR_PHY_TOP_15C            REG_15C;
	union REG_SENSOR_PHY_TOP_160            REG_160;
	union REG_SENSOR_PHY_TOP_164            REG_164;
	union REG_SENSOR_PHY_TOP_168            REG_168;
	union REG_SENSOR_PHY_TOP_16C            REG_16C;
	union REG_SENSOR_PHY_TOP_170            REG_170;
	union REG_SENSOR_PHY_TOP_174            REG_174;
	union REG_SENSOR_PHY_TOP_178            REG_178;
	union REG_SENSOR_PHY_TOP_17C            REG_17C;
	union REG_SENSOR_PHY_TOP_DFT_180        DFT_180;
	union REG_SENSOR_PHY_TOP_DFT_184        DFT_184;
	union REG_SENSOR_PHY_TOP_DFT_188        DFT_188;
	union REG_SENSOR_PHY_TOP_DFT_18C        DFT_18C;
	union REG_SENSOR_PHY_TOP_DFT_190        DFT_190;
	uint32_t                                _resv_0x194[23];
	union REG_SENSOR_PHY_TOP_DBG_1F0        DBG_1F0;
	uint32_t                                _resv_0x1f4[3];
	union REG_SENSOR_PHY_TOP_200            REG_200;
	union REG_SENSOR_PHY_TOP_204            REG_204;
	union REG_SENSOR_PHY_TOP_208            REG_208;
	union REG_SENSOR_PHY_TOP_20C            REG_20C;
	union REG_SENSOR_PHY_TOP_210            REG_210;
	union REG_SENSOR_PHY_TOP_214            REG_214;
	union REG_SENSOR_PHY_TOP_218            REG_218;
	union REG_SENSOR_PHY_TOP_21C            REG_21C;
	union REG_SENSOR_PHY_TOP_220            REG_220;
	union REG_SENSOR_PHY_TOP_224            REG_224;
	union REG_SENSOR_PHY_TOP_228            REG_228;
	union REG_SENSOR_PHY_TOP_22C            REG_22C;
	union REG_SENSOR_PHY_TOP_230            REG_230;
	union REG_SENSOR_PHY_TOP_234            REG_234;
	union REG_SENSOR_PHY_TOP_238            REG_238;
	union REG_SENSOR_PHY_TOP_23C            REG_23C;
	union REG_SENSOR_PHY_TOP_240            REG_240;
	union REG_SENSOR_PHY_TOP_244            REG_244;
	union REG_SENSOR_PHY_TOP_248            REG_248;
};

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_8L_T {
	union REG_SENSOR_PHY_8L_00              REG_00;
	union REG_SENSOR_PHY_8L_04              REG_04;
	union REG_SENSOR_PHY_8L_08              REG_08;
	union REG_SENSOR_PHY_8L_0C              REG_0C;
	union REG_SENSOR_PHY_8L_10              REG_10;
	union REG_SENSOR_PHY_8L_14              REG_14;
	uint32_t                                _resv_0x18[2];
	union REG_SENSOR_PHY_8L_20              REG_20;
	union REG_SENSOR_PHY_8L_24              REG_24;
	union REG_SENSOR_PHY_8L_28              REG_28;
	uint32_t                                _resv_0x2c[1];
	union REG_SENSOR_PHY_8L_30              REG_30;
	union REG_SENSOR_PHY_8L_34              REG_34;
	union REG_SENSOR_PHY_8L_38              REG_38;
	union REG_SENSOR_PHY_8L_3C              REG_3C;
	union REG_SENSOR_PHY_8L_40              REG_40;
	union REG_SENSOR_PHY_8L_44              REG_44;
	union REG_SENSOR_PHY_8L_48              REG_48;
	union REG_SENSOR_PHY_8L_4C              REG_4C;
	union REG_SENSOR_PHY_8L_50              REG_50;
	union REG_SENSOR_PHY_8L_54              REG_54;
	union REG_SENSOR_PHY_8L_58              REG_58;
	union REG_SENSOR_PHY_8L_5C              REG_5C;
	union REG_SENSOR_PHY_8L_60              REG_60;
	union REG_SENSOR_PHY_8L_64              REG_64;
	union REG_SENSOR_PHY_8L_68              REG_68;
	union REG_SENSOR_PHY_8L_6C              REG_6C;
	union REG_SENSOR_PHY_8L_70              REG_70;
	union REG_SENSOR_PHY_8L_74              REG_74;
	union REG_SENSOR_PHY_8L_78              REG_78;
	union REG_SENSOR_PHY_8L_7C              REG_7C;
	union REG_SENSOR_PHY_8L_80              REG_80;
	union REG_SENSOR_PHY_8L_84              REG_84;
	uint32_t                                _resv_0x88[2];
	union REG_SENSOR_PHY_8L_DBG_90          DBG_90;
	union REG_SENSOR_PHY_8L_DBG_94          DBG_94;
	union REG_SENSOR_PHY_8L_STATUS_98       STATUS_98;
	union REG_SENSOR_PHY_8L_STATUS_9C       STATUS_9C;
	union REG_SENSOR_PHY_8L_STATUS_A0       STATUS_A0;
	union REG_SENSOR_PHY_8L_STATUS_A4       STATUS_A4;
	union REG_SENSOR_PHY_8L_STATUS_A8       STATUS_A8;
	union REG_SENSOR_PHY_8L_STATUS_AC       STATUS_AC;
	uint32_t                                _resv_0xb0[20];
	union REG_SENSOR_PHY_8L_D0_0            D0_0;
	union REG_SENSOR_PHY_8L_D0_1            D0_1;
	union REG_SENSOR_PHY_8L_D0_2            D0_2;
	union REG_SENSOR_PHY_8L_D0_3            D0_3;
	union REG_SENSOR_PHY_8L_D0_4            D0_4;
	union REG_SENSOR_PHY_8L_D0_5            D0_5;
	union REG_SENSOR_PHY_8L_D0_6            D0_6;
	union REG_SENSOR_PHY_8L_D0_7            D0_7;
	union REG_SENSOR_PHY_8L_D0_8            D0_8;
	union REG_SENSOR_PHY_8L_D0_9            D0_9;
	union REG_SENSOR_PHY_8L_D0_A            D0_A;
	union REG_SENSOR_PHY_8L_D0_B            D0_B;
	uint32_t                                _resv_0x130[4];
	union REG_SENSOR_PHY_8L_D1_0            D1_0;
	union REG_SENSOR_PHY_8L_D1_1            D1_1;
	union REG_SENSOR_PHY_8L_D1_2            D1_2;
	union REG_SENSOR_PHY_8L_D1_3            D1_3;
	union REG_SENSOR_PHY_8L_D1_4            D1_4;
	union REG_SENSOR_PHY_8L_D1_5            D1_5;
	union REG_SENSOR_PHY_8L_D1_6            D1_6;
	union REG_SENSOR_PHY_8L_D1_7            D1_7;
	union REG_SENSOR_PHY_8L_D1_8            D1_8;
	union REG_SENSOR_PHY_8L_D1_9            D1_9;
	union REG_SENSOR_PHY_8L_D1_A            D1_A;
	union REG_SENSOR_PHY_8L_D1_B            D1_B;
	uint32_t                                _resv_0x170[4];
	union REG_SENSOR_PHY_8L_D2_0            D2_0;
	union REG_SENSOR_PHY_8L_D2_1            D2_1;
	union REG_SENSOR_PHY_8L_D2_2            D2_2;
	union REG_SENSOR_PHY_8L_D2_3            D2_3;
	union REG_SENSOR_PHY_8L_D2_4            D2_4;
	union REG_SENSOR_PHY_8L_D2_5            D2_5;
	union REG_SENSOR_PHY_8L_D2_6            D2_6;
	union REG_SENSOR_PHY_8L_D2_7            D2_7;
	union REG_SENSOR_PHY_8L_D2_8            D2_8;
	union REG_SENSOR_PHY_8L_D2_9            D2_9;
	union REG_SENSOR_PHY_8L_D2_A            D2_A;
	union REG_SENSOR_PHY_8L_D2_B            D2_B;
	uint32_t                                _resv_0x1b0[4];
	union REG_SENSOR_PHY_8L_D3_0            D3_0;
	union REG_SENSOR_PHY_8L_D3_1            D3_1;
	union REG_SENSOR_PHY_8L_D3_2            D3_2;
	union REG_SENSOR_PHY_8L_D3_3            D3_3;
	union REG_SENSOR_PHY_8L_D3_4            D3_4;
	union REG_SENSOR_PHY_8L_D3_5            D3_5;
	union REG_SENSOR_PHY_8L_D3_6            D3_6;
	union REG_SENSOR_PHY_8L_D3_7            D3_7;
	union REG_SENSOR_PHY_8L_D3_8            D3_8;
	union REG_SENSOR_PHY_8L_D3_9            D3_9;
	union REG_SENSOR_PHY_8L_D3_A            D3_A;
	union REG_SENSOR_PHY_8L_D3_B            D3_B;
	uint32_t                                _resv_0x1f0[4];
	union REG_SENSOR_PHY_8L_D4_0            D4_0;
	union REG_SENSOR_PHY_8L_D4_1            D4_1;
	union REG_SENSOR_PHY_8L_D4_2            D4_2;
	union REG_SENSOR_PHY_8L_D4_3            D4_3;
	union REG_SENSOR_PHY_8L_D4_4            D4_4;
	union REG_SENSOR_PHY_8L_D4_5            D4_5;
	union REG_SENSOR_PHY_8L_D4_6            D4_6;
	union REG_SENSOR_PHY_8L_D4_7            D4_7;
	union REG_SENSOR_PHY_8L_D4_8            D4_8;
	union REG_SENSOR_PHY_8L_D4_9            D4_9;
	union REG_SENSOR_PHY_8L_D4_A            D4_A;
	union REG_SENSOR_PHY_8L_D4_B            D4_B;
	uint32_t                                _resv_0x230[4];
	union REG_SENSOR_PHY_8L_D5_0            D5_0;
	union REG_SENSOR_PHY_8L_D5_1            D5_1;
	union REG_SENSOR_PHY_8L_D5_2            D5_2;
	union REG_SENSOR_PHY_8L_D5_3            D5_3;
	union REG_SENSOR_PHY_8L_D5_4            D5_4;
	union REG_SENSOR_PHY_8L_D5_5            D5_5;
	union REG_SENSOR_PHY_8L_D5_6            D5_6;
	union REG_SENSOR_PHY_8L_D5_7            D5_7;
	union REG_SENSOR_PHY_8L_D5_8            D5_8;
	union REG_SENSOR_PHY_8L_D5_9            D5_9;
	union REG_SENSOR_PHY_8L_D5_A            D5_A;
	union REG_SENSOR_PHY_8L_D5_B            D5_B;
	uint32_t                                _resv_0x270[4];
	union REG_SENSOR_PHY_8L_D6_0            D6_0;
	union REG_SENSOR_PHY_8L_D6_1            D6_1;
	union REG_SENSOR_PHY_8L_D6_2            D6_2;
	union REG_SENSOR_PHY_8L_D6_3            D6_3;
	union REG_SENSOR_PHY_8L_D6_4            D6_4;
	union REG_SENSOR_PHY_8L_D6_5            D6_5;
	union REG_SENSOR_PHY_8L_D6_6            D6_6;
	union REG_SENSOR_PHY_8L_D6_7            D6_7;
	union REG_SENSOR_PHY_8L_D6_8            D6_8;
	union REG_SENSOR_PHY_8L_D6_9            D6_9;
	union REG_SENSOR_PHY_8L_D6_A            D6_A;
	union REG_SENSOR_PHY_8L_D6_B            D6_B;
	uint32_t                                _resv_0x2b0[4];
	union REG_SENSOR_PHY_8L_D7_0            D7_0;
	union REG_SENSOR_PHY_8L_D7_1            D7_1;
	union REG_SENSOR_PHY_8L_D7_2            D7_2;
	union REG_SENSOR_PHY_8L_D7_3            D7_3;
	union REG_SENSOR_PHY_8L_D7_4            D7_4;
	union REG_SENSOR_PHY_8L_D7_5            D7_5;
	union REG_SENSOR_PHY_8L_D7_6            D7_6;
	union REG_SENSOR_PHY_8L_D7_7            D7_7;
	union REG_SENSOR_PHY_8L_D7_8            D7_8;
	union REG_SENSOR_PHY_8L_D7_9            D7_9;
	union REG_SENSOR_PHY_8L_D7_A            D7_A;
	union REG_SENSOR_PHY_8L_D7_B            D7_B;
};

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_4L_T {
	union REG_SENSOR_PHY_4L_00              REG_00;
	union REG_SENSOR_PHY_4L_04              REG_04;
	union REG_SENSOR_PHY_4L_08              REG_08;
	union REG_SENSOR_PHY_4L_0C              REG_0C;
	union REG_SENSOR_PHY_4L_10              REG_10;
	uint32_t                                _resv_0x14[3];
	union REG_SENSOR_PHY_4L_20              REG_20;
	union REG_SENSOR_PHY_4L_24              REG_24;
	union REG_SENSOR_PHY_4L_28              REG_28;
	uint32_t                                _resv_0x2c[1];
	union REG_SENSOR_PHY_4L_30              REG_30;
	union REG_SENSOR_PHY_4L_34              REG_34;
	union REG_SENSOR_PHY_4L_38              REG_38;
	union REG_SENSOR_PHY_4L_3C              REG_3C;
	union REG_SENSOR_PHY_4L_40              REG_40;
	union REG_SENSOR_PHY_4L_44              REG_44;
	union REG_SENSOR_PHY_4L_48              REG_48;
	union REG_SENSOR_PHY_4L_4C              REG_4C;
	union REG_SENSOR_PHY_4L_50              REG_50;
	union REG_SENSOR_PHY_4L_54              REG_54;
	union REG_SENSOR_PHY_4L_58              REG_58;
	union REG_SENSOR_PHY_4L_5C              REG_5C;
	union REG_SENSOR_PHY_4L_60              REG_60;
	union REG_SENSOR_PHY_4L_64              REG_64;
	uint32_t                                _resv_0x68[10];
	union REG_SENSOR_PHY_4L_DBG_90          DBG_90;
	union REG_SENSOR_PHY_4L_DBG_94          DBG_94;
	union REG_SENSOR_PHY_4L_STATUS_98       STATUS_98;
	union REG_SENSOR_PHY_4L_STATUS_9C       STATUS_9C;
	uint32_t                                _resv_0xa0[1];
	union REG_SENSOR_PHY_4L_STATUS_A4       STATUS_A4;
	union REG_SENSOR_PHY_4L_STATUS_A8       STATUS_A8;
	uint32_t                                _resv_0xac[21];
	union REG_SENSOR_PHY_4L_D0_0            D0_0;
	union REG_SENSOR_PHY_4L_D0_1            D0_1;
	union REG_SENSOR_PHY_4L_D0_2            D0_2;
	union REG_SENSOR_PHY_4L_D0_3            D0_3;
	union REG_SENSOR_PHY_4L_D0_4            D0_4;
	union REG_SENSOR_PHY_4L_D0_5            D0_5;
	union REG_SENSOR_PHY_4L_D0_6            D0_6;
	union REG_SENSOR_PHY_4L_D0_7            D0_7;
	union REG_SENSOR_PHY_4L_D0_8            D0_8;
	union REG_SENSOR_PHY_4L_D0_9            D0_9;
	union REG_SENSOR_PHY_4L_D0_A            D0_A;
	union REG_SENSOR_PHY_4L_D0_B            D0_B;
	uint32_t                                _resv_0x130[4];
	union REG_SENSOR_PHY_4L_D1_0            D1_0;
	union REG_SENSOR_PHY_4L_D1_1            D1_1;
	union REG_SENSOR_PHY_4L_D1_2            D1_2;
	union REG_SENSOR_PHY_4L_D1_3            D1_3;
	union REG_SENSOR_PHY_4L_D1_4            D1_4;
	union REG_SENSOR_PHY_4L_D1_5            D1_5;
	union REG_SENSOR_PHY_4L_D1_6            D1_6;
	union REG_SENSOR_PHY_4L_D1_7            D1_7;
	union REG_SENSOR_PHY_4L_D1_8            D1_8;
	union REG_SENSOR_PHY_4L_D1_9            D1_9;
	union REG_SENSOR_PHY_4L_D1_A            D1_A;
	union REG_SENSOR_PHY_4L_D1_B            D1_B;
	uint32_t                                _resv_0x170[4];
	union REG_SENSOR_PHY_4L_D2_0            D2_0;
	union REG_SENSOR_PHY_4L_D2_1            D2_1;
	union REG_SENSOR_PHY_4L_D2_2            D2_2;
	union REG_SENSOR_PHY_4L_D2_3            D2_3;
	union REG_SENSOR_PHY_4L_D2_4            D2_4;
	union REG_SENSOR_PHY_4L_D2_5            D2_5;
	union REG_SENSOR_PHY_4L_D2_6            D2_6;
	union REG_SENSOR_PHY_4L_D2_7            D2_7;
	union REG_SENSOR_PHY_4L_D2_8            D2_8;
	union REG_SENSOR_PHY_4L_D2_9            D2_9;
	union REG_SENSOR_PHY_4L_D2_A            D2_A;
	union REG_SENSOR_PHY_4L_D2_B            D2_B;
	uint32_t                                _resv_0x1b0[4];
	union REG_SENSOR_PHY_4L_D3_0            D3_0;
	union REG_SENSOR_PHY_4L_D3_1            D3_1;
	union REG_SENSOR_PHY_4L_D3_2            D3_2;
	union REG_SENSOR_PHY_4L_D3_3            D3_3;
	union REG_SENSOR_PHY_4L_D3_4            D3_4;
	union REG_SENSOR_PHY_4L_D3_5            D3_5;
	union REG_SENSOR_PHY_4L_D3_6            D3_6;
	union REG_SENSOR_PHY_4L_D3_7            D3_7;
	union REG_SENSOR_PHY_4L_D3_8            D3_8;
	union REG_SENSOR_PHY_4L_D3_9            D3_9;
	union REG_SENSOR_PHY_4L_D3_A            D3_A;
	union REG_SENSOR_PHY_4L_D3_B            D3_B;
};

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_SENSOR_PHY_2L_T {
	union REG_SENSOR_PHY_2L_00              REG_00;
	union REG_SENSOR_PHY_2L_04              REG_04;
	union REG_SENSOR_PHY_2L_08              REG_08;
	union REG_SENSOR_PHY_2L_0C              REG_0C;
	union REG_SENSOR_PHY_2L_10              REG_10;
	uint32_t                                _resv_0x14[3];
	union REG_SENSOR_PHY_2L_20              REG_20;
	union REG_SENSOR_PHY_2L_24              REG_24;
	union REG_SENSOR_PHY_2L_28              REG_28;
	uint32_t                                _resv_0x2c[1];
	union REG_SENSOR_PHY_2L_30              REG_30;
	union REG_SENSOR_PHY_2L_34              REG_34;
	union REG_SENSOR_PHY_2L_38              REG_38;
	union REG_SENSOR_PHY_2L_3C              REG_3C;
	union REG_SENSOR_PHY_2L_40              REG_40;
	union REG_SENSOR_PHY_2L_44              REG_44;
	union REG_SENSOR_PHY_2L_48              REG_48;
	union REG_SENSOR_PHY_2L_4C              REG_4C;
	union REG_SENSOR_PHY_2L_50              REG_50;
	union REG_SENSOR_PHY_2L_54              REG_54;
	uint32_t                                _resv_0x58[14];
	union REG_SENSOR_PHY_2L_DBG_90          DBG_90;
	union REG_SENSOR_PHY_2L_DBG_94          DBG_94;
	union REG_SENSOR_PHY_2L_STATUS_98       STATUS_98;
	union REG_SENSOR_PHY_2L_STATUS_9C       STATUS_9C;
	uint32_t                                _resv_0xa0[24];
	union REG_SENSOR_PHY_2L_D0_0            D0_0;
	union REG_SENSOR_PHY_2L_D0_1            D0_1;
	union REG_SENSOR_PHY_2L_D0_2            D0_2;
	union REG_SENSOR_PHY_2L_D0_3            D0_3;
	union REG_SENSOR_PHY_2L_D0_4            D0_4;
	union REG_SENSOR_PHY_2L_D0_5            D0_5;
	union REG_SENSOR_PHY_2L_D0_6            D0_6;
	union REG_SENSOR_PHY_2L_D0_7            D0_7;
	union REG_SENSOR_PHY_2L_D0_8            D0_8;
	union REG_SENSOR_PHY_2L_D0_9            D0_9;
	union REG_SENSOR_PHY_2L_D0_A            D0_A;
	union REG_SENSOR_PHY_2L_D0_B            D0_B;
	uint32_t                                _resv_0x130[4];
	union REG_SENSOR_PHY_2L_D1_0            D1_0;
	union REG_SENSOR_PHY_2L_D1_1            D1_1;
	union REG_SENSOR_PHY_2L_D1_2            D1_2;
	union REG_SENSOR_PHY_2L_D1_3            D1_3;
	union REG_SENSOR_PHY_2L_D1_4            D1_4;
	union REG_SENSOR_PHY_2L_D1_5            D1_5;
	union REG_SENSOR_PHY_2L_D1_6            D1_6;
	union REG_SENSOR_PHY_2L_D1_7            D1_7;
	union REG_SENSOR_PHY_2L_D1_8            D1_8;
	union REG_SENSOR_PHY_2L_D1_9            D1_9;
	union REG_SENSOR_PHY_2L_D1_A            D1_A;
	union REG_SENSOR_PHY_2L_D1_B            D1_B;
};

#ifdef __cplusplus
}
#endif

#endif /* _REG_BLOCKS_CSI_WRAP_H_ */
