#ifndef _UT_ERRNO_H_
#define _UT_ERRNO_H_

enum cvi_errno {
	ERR_NONE = 0,
	ERR_MSG_NO_DST,
	ERR_DEVICE_CLOSE,
	ERR_IOCTL,
	ERR_IOCTL_NO_REQ,
	ERR_IOCTL_VIDIOC_TRY_EXT_CTRLS,//5
	ERR_IOCTL_VIDIOC_G_EXT_CTRLS,
	ERR_IOCTL_VIDIOC_S_EXT_CTRLS,
	ERR_IOCTL_VIDIOC_DQEVENT,
	ERR_IOCTL_VIDIOC_DQBUF,
	ERR_IOCTL_VIDIOC_QBUF,//10
	ERR_IOCTL_VIDIOC_QUERYCAP,
	ERR_IOCTL_VIDIOC_UNSUBSCRIBE_EVENT,
	ERR_IOCTL_VIDIOC_SUBSCRIBE_EVENT,
	ERR_IOCTL_VIDIOC_S_FMT,
	ERR_IOCTL_VIDIOC_TRY_FMT,//15
	ERR_IOCTL_VIDIOC_STREAMOFF,
	ERR_IOCTL_VIDIOC_STREAMON,

	ISP_ERR_CODE = 0x100000,
	ISP_ERR_WAIT_EVENT_TIMEOUT,
	ISP_ERR_WAIT_EVENT,
	ISP_ERR_DQBUF_BA,

	SCLR_ERR_CODE = 0x200000,

	ERR_CODE_MAX,
};

#endif
