#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8188FU)     	+= rtl8188f/
obj-$(CONFIG_RTL8189FS)     	+= rtl8189fs/
obj-$(CONFIG_RTL8852BE) += rtl8852be/
obj-m += rtl8822ce/
obj-m += rtl8852ce/
