#ifndef _DPU_REG_
#define _DPU_REG_

// #define _DPU_BASE_ADDR                          (0x680ba600)
// #define _DPU_SGBM_LD1_BASE_ADDR                 (0x680ba000)
// #define _DPU_SGBM_LD2_BASE_ADDR                 (0x680ba100)
// #define _DPU_FGS_CHFH_LD_BASE_ADDR              (0x680ba200)
// #define _DPU_FGS_GX_LD_BASE_ADDR                (0x680ba300)
// #define _DPU_SGBM_BTCOST_ST_BASE_ADDR           (0x680bb000)  
// #define _DPU_SGBM_MEDIAN_ST_BASE_ADDR           (0x680bb100)
// #define _DPU_FGS_CHFH_ST_BASE_ADDR              (0x680bb200)
// #define _DPU_FGS_UX_ST_BASE_ADDR                (0x680bb300)

#define DPU_REG_00_OFS                         (0x00)
#define DPU_REG_04_OFS                         (0x04)
#define DPU_REG_08_OFS                         (0x08)
#define DPU_REG_0C_OFS                         (0x0C)
#define DPU_REG_10_OFS                         (0x10)
#define DPU_REG_14_OFS                         (0x14)
#define DPU_REG_18_OFS                         (0x18)
#define DPU_REG_1C_OFS                         (0x1C)
#define DPU_REG_20_OFS                         (0x20)
#define DPU_REG_24_OFS                         (0x24)
#define DPU_REG_28_OFS                         (0x28)
#define DPU_REG_2C_OFS                         (0x2C)
#define DPU_REG_30_OFS                         (0x30)
#define DPU_REG_34_OFS                         (0x34)
#define DPU_REG_38_OFS                         (0x38)
#define DPU_REG_3C_OFS                         (0x3C)
#define DPU_REG_40_OFS                         (0x40)
#define DPU_REG_44_OFS                         (0x44)
#define DPU_REG_48_OFS                         (0x48)
#define DPU_REG_4C_OFS                         (0x4C)
#define DPU_REG_50_OFS                         (0x50)
#define DPU_REG_54_OFS                         (0x54)
#define DPU_REG_58_OFS                         (0x58)
#define DPU_REG_5C_OFS                         (0x5C)
#define DPU_REG_60_OFS                         (0x60)
#define DPU_REG_64_OFS                         (0x64)
#define DPU_REG_68_OFS                         (0x68)
#define DPU_REG_6C_OFS                         (0x6C)
#define DPU_REG_70_OFS                         (0x70)
#define DPU_REG_74_OFS                         (0x74)
#define DPU_REG_78_OFS                         (0x78)
#define DPU_REG_7C_OFS                         (0x7C)
#define DPU_REG_80_OFS                         (0x80)
#define DPU_REG_84_OFS                         (0x84)
#define DPU_REG_88_OFS                         (0x88)
#define DPU_REG_8C_OFS                         (0x8C)
#define DPU_REG_90_OFS                         (0x90)
#define DPU_REG_94_OFS                         (0x94)
#define DPU_REG_98_OFS                         (0x98)
#define DPU_REG_9C_OFS                         (0x9C)
#define DPU_REG_A0_OFS                         (0xA0)

#define SYS_CONTROL_OFS                        (0x00)
#define DMA_BASE_ADDR_OFS                      (0x04)   // 16 aligned
#define DMA_SEGLEN_OFS                         (0x08)
#define DMA_STRIDE_OFS                         (0x0c)
#define DMA_SEGNUM_OFS                         (0x10)
#define DMA_STATUS_OFS                         (0x14)
#define DMA_SLICESIZE_OFS                      (0x18)
#define DMA_DUMMY_OFS                          (0x1c)
#define DMA_PATCH_OFS                          (0x1c)

#define REG_ENABLE_INV_MASK                    (0x4)


#define REG(name) (DPU_BASE_ADDR + DPU_REG_##name##_OFS)

//base addr shift
// #define DPU_REG_00_OFS                      (0x00)
// #define DPU_REG_04_OFS                      (0x04)
// #define DPU_REG_08_OFS                      (0x08)
// #define DPU_REG_0C_OFS                      (0x0C)
// #define DPU_REG_10_OFS                      (0x10)
// #define DPU_REG_14_OFS                      (0x14)
// #define DPU_REG_18_OFS                      (0x18)
// #define DPU_REG_1C_OFS                      (0x1C)
// #define DPU_REG_68_OFS                      (0x68)

// #define DPU_DMA_REG_04_OFS                  (0x04)
// #define DPU_DMA_REG_08_OFS                  (0x08)
// #define DPU_DMA_REG_0C_OFS                  (0x0C)
// #define DPU_DMA_REG_10_OFS                  (0x10)

// //reg shift
// #define DPU_ENABLE_SHIFT                    (0U)
// #define DPU_IMAGE_WIDTH_SHIFT               (0U)
// #define DPU_IMAGE_HEIGHT_SHIFT              (16U)
// #define DPU_MIN_D_SHIFT                     (0U)
// #define DPU_MAX_D_SHIFT                     (8U)
// #define DPU_KW_SHIFT                        (16U)
// #define DPU_KH_SHIFT                        (24U)
// #define DPU_SOBEL_FILTERCAP_SHIFT           (0U)
// #define DPU_RSHIFT1_SHIFT                   (8U)
// #define DPU_RSHIFT2_SHIFT                   (12U)
// #define DPU_CA_P1_SHIFT                     (0U)
// #define DPU_CA_P2_SHIFT                     (16U)
// #define DPU_UNIQ_RATIO_SHIFT                (0U)
// #define DPU_DISP_SHIFT_SHIFT                (8U)
// #define DPU_DISP12_MAX_DIFF_SHIFT           (12U)
// #define DPU_BFW_SIZE_SHIFT                  (16U)
// #define DPU_CENSUS_SHIFT_SHIFT              (18U)
// #define DPU_FGS_MAX_COUNT_SHIFT             (0U)
// #define DPU_FGS_MAX_T_SHIFT                 (5U)
// #define DPU_FGS_W_SCALE_SHIFT               (8U)
// #define DPU_FGS_C_SCALE_SHIFT               (12U)
// #define DPU_FGS_F_SCALE_SHIFT               (16U)

// #define DPU_FRAME_START_SHIFT               (0U)
// #define DPU_FRAME_DONE_SHIFT                (1U)
// #define DPU_FRAME_RESET_SHIFT               (6U)
// #define DPU_FRAME_INTR_CLR_SHIFT            (9U)

// #define DPU_DMA_ADDR_SHIFT                  (0U)
// #define DPU_DMA_SEGLEN_SHIFT                (0U)
// #define DPU_DMA_STRIDE_SHIFT                (0U)
// #define DPU_DMA_SEGNUM_SHIFT                (0U)

// //reg size
// #define DPU_ENABLE_SIZE                     (1U)
// #define DPU_IMAGE_WIDTH_SIZE                (16U)
// #define DPU_IMAGE_HEIGHT_SIZE               (16U)
// #define DPU_MIN_D_SIZE                      (8U)
// #define DPU_MAX_D_SIZE                      (8U)
// #define DPU_KW_SIZE                         (8U)
// #define DPU_KH_SIZE                         (8U)
// #define DPU_SOBEL_FILTERCAP_SIZE            (7U)
// #define DPU_RSHIFT1_SIZE                    (3U)
// #define DPU_RSHIFT2_SIZE                    (3U)
// #define DPU_CA_P1_SIZE                      (16U)
// #define DPU_CA_P2_SIZE                      (16U)
// #define DPU_UNIQ_RATIO_SIZE                 (8U)
// #define DPU_DISP_SHIFT_SIZE                 (4U)
// #define DPU_DISP12_MAX_DIFF_SIZE            (4U)
// #define DPU_BFW_SIZE_SIZE                   (2U)
// #define DPU_CENSUS_SHIFT_SIZE               (8U)
// #define DPU_FGS_MAX_COUNT_SIZE              (5U)
// #define DPU_FGS_MAX_T_SIZE                  (3U)
// #define DPU_FGS_W_SCALE_SIZE                (4U)
// #define DPU_FGS_C_SCALE_SIZE                (4U)
// #define DPU_FGS_F_SCALE_SIZE                (4U)

// #define DPU_FRAME_START_SIZE                (1U)
// #define DPU_FRAME_DONE_SIZE                 (1U) 
// #define DPU_FRAME_RESET_SIZE                (1U)
// #define DPU_FRAME_INTR_CLR_SIZE             (1U)

// #define DPU_DMA_ADDR_SIZE                   (32U)
// #define DPU_DMA_SEGLEN_SIZE                 (28U)
// #define DPU_DMA_STRIDE_SIZE                 (28U)
// #define DPU_DMA_SEGNUM_SIZE                 (14U)

// //reg mask
// #define DPU_ENABLE_MASK                     (((1 << DPU_ENABLE_SIZE)-1) << DPU_ENABLE_SHIFT)
// #define DPU_IMAGE_WIDTH_MASK                (((1 << DPU_IMAGE_WIDTH_SIZE)-1) << DPU_IMAGE_WIDTH_SHIFT)
// #define DPU_IMAGE_HEIGHT_MASK               (((1 << DPU_IMAGE_HEIGHT_SIZE)-1) << DPU_IMAGE_HEIGHT_SHIFT)
// #define DPU_MIN_D_MASK                      (((1 << DPU_MIN_D_SIZE)-1) << DPU_MIN_D_SHIFT)
// #define DPU_MAX_D_MASK                      (((1 << DPU_MAX_D_SIZE)-1) << DPU_MAX_D_SHIFT)
// #define DPU_KW_MASK                         (((1 << DPU_KW_SIZE)-1) << DPU_KW_SHIFT)
// #define DPU_KH_MASK                         (((1 << DPU_KH_SIZE)-1) << DPU_KH_SHIFT)
// #define DPU_SOBEL_FILTERCAP_MASK            (((1 << DPU_SOBEL_FILTERCAP_SIZE)-1) << DPU_SOBEL_FILTERCAP_SHIFT)
// #define DPU_RSHIFT1_MASK                    (((1 << DPU_SRSHIFT1_SIZE)-1) << DPU_RSHIFT1_SHIFT)
// #define DPU_RSHIFT2_MASK                    (((1 << DPU_SRSHIFT2_SIZE)-1) << DPU_RSHIFT2_SHIFT)
// #define DPU_CA_P1_MASK                      (((1 << DPU_CA_P1_SIZE)-1) << DPU_CA_P1_SHIFT)
// #define DPU_CA_P2_MASK                      (((1 << DPU_CA_P2_SIZE)-1) << DPU_CA_P2_SHIFT)
// #define DPU_UNIQ_RATIO_MASK                 (((1 << DPU_UNIQ_RATIO_SIZE)-1) << DPU_UNIQ_RATIO_SHIFT)
// #define DPU_DISP_SHIFT_MASK                 (((1 << DPU_DISP_SHIFT_SIZE)-1) << DPU_DISP_SHIFT_SHIFT)
// #define DPU_DISP12_MAX_DIFF_MASK            (((1 << DPU_DISP12_MAX_DIFF_SIZE)-1) << DPU_DISP12_MAX_DIFF_SHIFT)
// #define DPU_BFW_SIZE_MASK                   (((1 << DPU_BFW_SIZE_SIZE)-1) << DPU_BFW_SIZE_SHIFT)
// #define DPU_CENSUS_SHIFT_MASK               (((1 << DPU_CENSUS_SHIFT_SIZE)-1) << DPU_CENSUS_SHIFT_SHIFT)
// #define DPU_FGS_MAX_COUNT_MASK              (((1 << DPU_FGS_MAX_COUNT_SIZE)-1) << DPU_FGS_MAX_COUNT_SHIFT)
// #define DPU_FGS_MAX_T_MASK                  (((1 << DPU_FGS_MAX_T_SIZE)-1) << DPU_FGS_MAX_T_SHIFT)
// #define DPU_FGS_W_SCALE_MASK                (((1 << DPU_FGS_W_SCALE_SIZE)-1) << DPU_FGS_W_SCALE_SHIFT)
// #define DPU_FGS_C_SCALE_MASK                (((1 << DPU_FGS_C_SCALE_SIZE)-1) << DPU_FGS_C_SCALE_SHIFT)
// #define DPU_FGS_F_SCALE_MASK                (((1 << DPU_FGS_F_SCALE_SIZE)-1) << DPU_FGS_F_SCALE_SHIFT)

// #define DPU_FRAME_START_MASK                (((1 << DPU_FRAME_START_SIZE)-1) << DPU_FRAME_START_SHIFT)
// #define DPU_FRAME_DONE_MASK                 (((1 << DPU_FRAME_DONE_SIZE)-1) << DPU_FRAME_DONE_SHIFT) 
// #define DPU_FRAME_RESET_MASK                (((1 << DPU_FRAME_RESET_SIZE)-1) << DPU_FRAME_RESET_SHIFT)
// #define DPU_FRAME_INTR_CLR_MASK             (((1 << DPU_FRAME_INTR_CLR_SIZE)-1) << DPU_FRAME_INTR_CLR_SHIFT)

// #define DPU_DMA_ADDR_MASK                   (((1 << DPU_DMA_ADDR_SIZE)-1) << DPU_DMA_ADDR_SHIFT)
// #define DPU_DMA_SEGLEN_MASK                 (((1 << DPU_DMA_SEGLEN_SIZE)-1) << DPU_DMA_SEGLEN_SHIFT)
// #define DPU_DMA_STRIDE_MASK                 (((1 << DPU_DMA_STRIDE_SIZE)-1) << DPU_DMA_STRIDE_SHIFT)
// #define DPU_DMA_SEGNUM_MASK                 (((1 << DPU_DMA_SEGNUM_SIZE)-1) << DPU_DMA_SEGNUM_SHIFT)

#endif
