/*
 * Copyright (C) Cvitek Co., Ltd. 2019-2021. All rights reserved.
 *
 * File Name:stitch_reg_blocks.h
 * Description:HW register description
 */

#ifndef _STITCH_REG_BLOCKS_H_
#define _STITCH_REG_BLOCKS_H_

#ifdef __cplusplus
extern "C" {
#endif

/******************************************/
/*           Module Definition            */
/******************************************/
struct REG_STITCHING_BLENDING_T {
	union REG_STITCHING_BLENDING_0          REG_0;
	union REG_STITCHING_BLENDING_1          REG_1;
	union REG_STITCHING_BLENDING_2          REG_2;
	union REG_STITCHING_BLENDING_3          REG_3;
	union REG_STITCHING_BLENDING_4          REG_4;
	union REG_STITCHING_BLENDING_5          REG_5;
	union REG_STITCHING_BLENDING_6          REG_6;
	union REG_STITCHING_BLENDING_7          REG_7;
	union REG_STITCHING_BLENDING_8          REG_8;
	union REG_STITCHING_BLENDING_9          REG_9;
	uint32_t                                _resv_0x28[2];
	union REG_STITCHING_BLENDING_10         REG_10;
	union REG_STITCHING_BLENDING_11         REG_11;
	union REG_STITCHING_BLENDING_12         REG_12;
	union REG_STITCHING_BLENDING_13         REG_13;
	union REG_STITCHING_BLENDING_14         REG_14;
	union REG_STITCHING_BLENDING_15         REG_15;
	union REG_STITCHING_BLENDING_16         REG_16;
	union REG_STITCHING_BLENDING_17         REG_17;
	union REG_STITCHING_BLENDING_18         REG_18;
	union REG_STITCHING_BLENDING_19         REG_19;
	union REG_STITCHING_BLENDING_20         REG_20;
	union REG_STITCHING_BLENDING_21         REG_21;
	union REG_STITCHING_BLENDING_22         REG_22;
	union REG_STITCHING_BLENDING_23         REG_23;
	union REG_STITCHING_BLENDING_24         REG_24;
	union REG_STITCHING_BLENDING_25         REG_25;
	union REG_STITCHING_BLENDING_26         REG_26;
	union REG_STITCHING_BLENDING_27         REG_27;
	union REG_STITCHING_BLENDING_28         REG_28;
	union REG_STITCHING_BLENDING_29         REG_29;
	union REG_STITCHING_BLENDING_30         REG_30;
	union REG_STITCHING_BLENDING_31         REG_31;
	union REG_STITCHING_BLENDING_32         REG_32;
	union REG_STITCHING_BLENDING_33         REG_33;
	union REG_STITCHING_BLENDING_34         REG_34;
	union REG_STITCHING_BLENDING_35         REG_35;
	union REG_STITCHING_BLENDING_36         REG_36;
	union REG_STITCHING_BLENDING_37         REG_37;
	union REG_STITCHING_BLENDING_38         REG_38;
	union REG_STITCHING_BLENDING_39         REG_39;
	union REG_STITCHING_BLENDING_40         REG_40;
	union REG_STITCHING_BLENDING_41         REG_41;
	union REG_STITCHING_BLENDING_42         REG_42;
	union REG_STITCHING_BLENDING_43         REG_43;
	union REG_STITCHING_BLENDING_FLOW_CONTROL  FLOW_CONTROL;
	union REG_STITCHING_BLENDING_STCH_SHDW_SEL  STCH_SHDW_SEL;
	union REG_STITCHING_BLENDING_44         REG_44;
	union REG_STITCHING_BLENDING_45         REG_45;
	union REG_STITCHING_BLENDING_46         REG_46;
	union REG_STITCHING_BLENDING_47         REG_47;
	union REG_STITCHING_BLENDING_48         REG_48;
	union REG_STITCHING_BLENDING_49         REG_49;
	union REG_STITCHING_BLENDING_50         REG_50;
	union REG_STITCHING_BLENDING_51         REG_51;
	union REG_STITCHING_BLENDING_52         REG_52;
	union REG_STITCHING_BLENDING_53         REG_53;
	union REG_STITCHING_BLENDING_54         REG_54;
	union REG_STITCHING_BLENDING_55         REG_55;
	union REG_STITCHING_BLENDING_56         REG_56;
	union REG_STITCHING_BLENDING_57         REG_57;
	union REG_STITCHING_BLENDING_58         REG_58;
	union REG_STITCHING_BLENDING_59         REG_59;
	union REG_STITCHING_BLENDING_60         REG_60;
	union REG_STITCHING_BLENDING_61         REG_61;
	union REG_STITCHING_BLENDING_62         REG_62;
	union REG_STITCHING_BLENDING_63         REG_63;
	union REG_STITCHING_BLENDING_64         REG_64;
	union REG_STITCHING_BLENDING_65         REG_65;
	union REG_STITCHING_BLENDING_66         REG_66;
	union REG_STITCHING_BLENDING_67         REG_67;
	union REG_STITCHING_BLENDING_68         REG_68;
	union REG_STITCHING_BLENDING_69         REG_69;
	union REG_STITCHING_BLENDING_70         REG_70;
	union REG_STITCHING_BLENDING_71         REG_71;
	union REG_STITCHING_BLENDING_72         REG_72;
	union REG_STITCHING_BLENDING_73         REG_73;
	union REG_STITCHING_BLENDING_74         REG_74;
	union REG_STITCHING_BLENDING_75         REG_75;
	union REG_STITCHING_BLENDING_76         REG_76;
	union REG_STITCHING_BLENDING_77         REG_77;
	union REG_STITCHING_BLENDING_78         REG_78;
	union REG_STITCHING_BLENDING_79         REG_79;
	union REG_STITCHING_BLENDING_80         REG_80;
	union REG_STITCHING_BLENDING_81         REG_81;
	union REG_STITCHING_BLENDING_82         REG_82;
	union REG_STITCHING_BLENDING_83         REG_83;
	union REG_STITCHING_BLENDING_84         REG_84;
	union REG_STITCHING_BLENDING_85         REG_85;
	union REG_STITCHING_BLENDING_86         REG_86;
	union REG_STITCHING_BLENDING_MODE_SEL   MODE_SEL;
	union REG_STITCHING_BLENDING_SRC_SEL    SRC_SEL;
	union REG_STITCHING_BLENDING_87         REG_87;
	union REG_STITCHING_BLENDING_88         REG_88;
	union REG_STITCHING_BLENDING_89         REG_89;
	union REG_STITCHING_BLENDING_90         REG_90;
	union REG_STITCHING_BLENDING_91         REG_91;
	union REG_STITCHING_BLENDING_92         REG_92;
	union REG_STITCHING_BLENDING_93         REG_93;
	union REG_STITCHING_BLENDING_94         REG_94;
	union REG_STITCHING_BLENDING_95         REG_95;
	union REG_STITCHING_BLENDING_96         REG_96;
	union REG_STITCHING_BLENDING_97         REG_97;
	union REG_STITCHING_BLENDING_98         REG_98;
	union REG_STITCHING_BLENDING_INT_MASK   INT_MASK;
};

struct REG_STITCH_DMA_CTL_T {
	union REG_STITCH_DMA_CTL_SYS_CONTROL	SYS_CONTROL;
	union REG_STITCH_DMA_CTL_BASE_ADDR		BASE_ADDR;
	union REG_STITCH_DMA_CTL_DMA_SEGLEN 	DMA_SEGLEN;
	union REG_STITCH_DMA_CTL_DMA_STRIDE 	DMA_STRIDE;
	union REG_STITCH_DMA_CTL_DMA_SEGNUM 	DMA_SEGNUM;
	union REG_STITCH_DMA_CTL_DMA_STATUS 	DMA_STATUS;
	union REG_STITCH_DMA_CTL_DMA_SLICESIZE	DMA_SLICESIZE;
	union REG_STITCH_DMA_CTL_DMA_DUMMY		DMA_DUMMY;
};

#ifdef __cplusplus
}
#endif

#endif /* _STITCH_REG_BLOCKS_H_ */
