#include <linux/types.h>
#include <linux/version.h>
#include <linux/delay.h>
#include <linux/dma-buf.h>
#include <asm/cacheflush.h>
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0))
#include <linux/dma-map-ops.h>
#endif

#include "vi_sys.h"
#include "reg.h"
#include "stitch_reg_fields.h"
#include "stitch_reg_blocks.h"
#include "stitch_reg_cfg.h"
#include "stitch_cfg.h"
#include "stitch_debug.h"

#define STITCH_RST_VI_SYS_APB 1
#define STITCH_RST_VI_SYS_STITCH 0
#define STITCH_RST_STITCH 1

/****************************************************************************
 * Global parameters
 ***************************************************************************/
static uintptr_t reg_base;
static unsigned char wgt_disable[2], bld_disable[2];
static unsigned char drop_mode = 1;

/****************************************************************************
 * Initial info
 ***************************************************************************/
extern int gStitchDumpReg;
extern bool gStitchDumpDmaCfg;

static uintptr_t stitch_dma[STITCH_DMA_REG_NUM] = {
#if 0
	ADDR_WDMA_STCH_LEFTY0,   //id:0
	ADDR_WDMA_STCH_LEFTU0,
	ADDR_WDMA_STCH_LEFTV0,

	ADDR_WDMA_STCH_RIGHTY0,  //id:3
	ADDR_WDMA_STCH_RIGHTU0,
	ADDR_WDMA_STCH_RIGHTV0,

	ADDR_WDMA_STCH_BLDY0,    //id:6
	ADDR_WDMA_STCH_BLDU0,
	ADDR_WDMA_STCH_BLDV0,

	ADDR_WDMA_STCH_BLDY1,    //id:9
	ADDR_WDMA_STCH_BLDU1,
	ADDR_WDMA_STCH_BLDV1,

	ADDR_RDMA_STCH_LEFTY0,   //id:12
	ADDR_RDMA_STCH_LEFTU0,
	ADDR_RDMA_STCH_LEFTV0,

	ADDR_RDMA_STCH_RIGHTY0,  //id:15
	ADDR_RDMA_STCH_RIGHTU0,
	ADDR_RDMA_STCH_RIGHTV0,

	ADDR_RDMA_STCH_LEFTY1,   //id:18
	ADDR_RDMA_STCH_LEFTU1,
	ADDR_RDMA_STCH_LEFTV1,

	ADDR_RDMA_STCH_RIGHTY1,  //id:21
	ADDR_RDMA_STCH_RIGHTU1,
	ADDR_RDMA_STCH_RIGHTV1,

	ADDR_RDMA_STCH_ALPHA0,   //id:24
	ADDR_RDMA_STCH_BETA0,

	ADDR_RDMA_STCH_ALPHA1,   //id:26
	ADDR_RDMA_STCH_BETA1
#endif
};

/****************************************************************************
 * Interfaces
 ****************************************************************************/

void stitch_set_base_addr(void *base, void *dma_base)
{
	uintptr_t stitch_dma_ctrl;
	int i;

	reg_base = (uintptr_t)base;
	stitch_dma_ctrl = (uintptr_t)dma_base;

	TRACE_STITCH(DBG_DEBUG, "reg_base-stitch_dma_ctrl(%#lx-%#lx)\n", reg_base, stitch_dma_ctrl);

	stitch_dma[0] = stitch_dma_ctrl;
	for (i = 1; i < STITCH_DMA_REG_NUM; i++) {
		stitch_dma_ctrl += 0x80;

		if (i == ID_WDMA_STCH_BLDY1)
			stitch_dma_ctrl += 0x380;
		else if (i == ID_RDMA_STCH_LEFTY0)
			stitch_dma_ctrl += 0x180;

		stitch_dma[i] = stitch_dma_ctrl;
	}
}

/**
 * stitch_reset_vi_sys - do reset. This can be activated only if dma stop to avoid hang
 *	       fabric.
 *
 */
static void stitch_reset_vi_sys(void)
{
#if 1
	union vi_sys_reset mask;
	union vi_sys_reset_apb mask_apb;

#if STITCH_RST_VI_SYS_STITCH
	mask.raw = 0;
	mask.b.stitching = 1;

	vi_sys_toggle_reset(mask);
#else
	(void)mask;
#endif

#if STITCH_RST_VI_SYS_APB
		mask_apb.raw = 0;
		mask_apb.b.stitching = 1;

		vi_sys_toggle_reset_apb(mask_apb);
#else
		(void)mask_apb;
#endif

#endif
}

static void stitch_set_drop_mode(unsigned char drop_mode)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, DROP_MODE_BLD0, drop_mode);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, DROP_MODE_LEFT0, drop_mode);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, DROP_MODE_RIGHT0, drop_mode);
}

void stitch_reset_init(void)
{
	stitch_reset_vi_sys();

#if STITCH_RST_STITCH
	udelay(1000);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, SUBSYS_RESET_W1P, 0);
	//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, RESET_DONE, 0);//ro
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, TRIG_CNT, 0);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, SHADOW_CNT, 0);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, RESET_CNT, 0);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, STCH_SHDW_SEL, STCH_SHDW_SEL, 1);
	udelay(1000*10);
	udelay(1000*10);
	stitch_intr_clr();
	udelay(1000);
#endif
}

void stitch_enable(void)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, FRAME_START_W1P, 1);
}
void stitch_disable(void)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, FRAME_START_W1P, 0);
}

//enable top_wp0/top_wp1
//top_id: top_wp0/top_wp1
void stitch_valid_param(unsigned char top_id)
{
	if (!top_id) {
		//bld0_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_ALPHA0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_BETA0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTY0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTU0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTV0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTY0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTU0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTV0_ENABLE, 1);
		//bld0_wdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTY0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTU0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTV0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTY0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTU0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTV0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDY0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDU0_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDV0_ENABLE, 1);
		//crop
		STITCH_WR_REG(reg_base, REG_STITCHING_BLENDING_T, REG_86, 0x3FFF);
	}else {
		//bld1_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_ALPHA1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_BETA1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTY1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTU1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTV1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTY1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTU1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTV1_ENABLE, 1);
		//bld1_wdma
#if 0   //always close
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDY1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDU1_ENABLE, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDV1_ENABLE, 1);
		//crop
		STITCH_WR_REG(reg_base, REG_STITCHING_BLENDING_T, REG_86, 0x3FF0000);
	}
	stitch_set_drop_mode(drop_mode);
}

//disable top_wp0/top_wp1
//top_id: top_wp0/top_wp1
void stitch_invalid_param(unsigned char top_id)
{
	if (!top_id) {
		//bld0_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_ALPHA0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_BETA0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTV0_ENABLE, 0);
		//bld0_wdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDV0_ENABLE, 0);
		//crop
		//STITCH_WR_REG(reg_base, REG_STITCHING_BLENDING_T, REG_86, 0x3FFF);
	}else {
		//bld1_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_ALPHA1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_BETA1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTV1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTV1_ENABLE, 0);
		//bld1_wdma
#if 0   //always close
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDV1_ENABLE, 0);
		//crop
		//STITCH_WR_REG(reg_base, REG_STITCHING_BLENDING_T, REG_86, 0x3FF0000);
	}
	stitch_uv_bypass_clr(top_id);
	stitch_set_drop_mode(0);
}

void stitch_disable_wgt(unsigned char top_id)
{
	if (!top_id) {
		//wgt0_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_ALPHA0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_BETA0_ENABLE, 0);

		wgt_disable[0] = 1;
	} else {
		//wgt1_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_ALPHA1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_BETA1_ENABLE, 0);

		wgt_disable[1] = 1;
	}
}

void stitch_disable_bld(unsigned char top_id)
{
	if (!top_id) {
		//bld0_wdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDV0_ENABLE, 0);

		bld_disable[0] = 1;
	} else {
		//bld1_wdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDV1_ENABLE, 0);

		bld_disable[1] = 1;
	}
}

void stitch_disable_left_right_rdma(unsigned char top_id)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTV0_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTV0_ENABLE, 0);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTV1_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTV1_ENABLE, 0);

	}
}

void stitch_disable_left_rdma(unsigned char top_id)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTV0_ENABLE, 0);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTV1_ENABLE, 0);
	}
}

void stitch_disable_right_rdma(unsigned char top_id)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTV0_ENABLE, 0);
	}else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTV1_ENABLE, 0);
	}
}

void stitch_disable_left_right_wdma(unsigned char top_id)
{
	if (!top_id) {

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTV0_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTV0_ENABLE, 0);
	}else {
#if 0   //always close

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
	}
}

void stitch_disable_left_wdma(unsigned char top_id)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTV0_ENABLE, 0);
	}else {
#if 0   //always close
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
	}
}

void stitch_disable_right_wdma(unsigned char top_id)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTY0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTV0_ENABLE, 0);
	}else {
#if 0   //always close
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTY1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
	}
}

void stitch_r_uv_bypass(unsigned char sel)
{
	if (!sel) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTIN0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTIN0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTIN0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTIN0, 1);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTIN1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTIN1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTIN1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTIN1, 1);
	}
}

void stitch_w_uv_bypass(unsigned char sel)
{
	if (!sel) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_BLD0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_BLD0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTOUT0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTOUT0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTOUT0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTOUT0, 1);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_BLD1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_BLD1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTOUT1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTOUT1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTOUT1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTOUT1, 1);
	}
}

void stitch_r_uv_half_bypass(unsigned char sel)
{
	if (!sel) {
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTIN0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTIN0, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTIN0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTIN0, 1);
	} else {
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTIN1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTIN1, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTIN1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTIN1, 1);
	}
}

void stitch_w_uv_half_bypass(unsigned char sel)
{
	if (!sel) {
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_BLD0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_BLD0, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTOUT0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTOUT0, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTOUT0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTOUT0, 1);
	} else {
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_BLD1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_BLD1, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTOUT1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTOUT1, 1);
		//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTOUT1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTOUT1, 1);
	}
}

static void stitch_r_uv_bypass_clr(unsigned char sel)
{
	if (!sel) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTIN0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTIN0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTIN0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTIN0, 0);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTIN1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTIN1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTIN1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTIN1, 0);
	}
}

static void stitch_w_uv_bypass_clr(unsigned char sel)
{
	if (!sel) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_BLD0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_BLD0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_LEFTOUT0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_LEFTOUT0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_H_RIGHTOUT0, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_20, BYPASS_V_RIGHTOUT0, 0);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_BLD1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_BLD1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_LEFTOUT1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_LEFTOUT1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_42, BYPASS_H_RIGHTOUT1, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_43, BYPASS_V_RIGHTOUT1, 0);
	}
}

void stitch_uv_bypass_clr(unsigned char sel)
{
	stitch_r_uv_bypass_clr(sel);
	stitch_w_uv_bypass_clr(sel);
}

void stitch_disable_uv(unsigned char sel)
{
	if (!sel) {
		//bld0_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_LEFTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_16, RDMA_STCH_RIGHTV0_ENABLE, 0);
		//bld0_wdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_LEFTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_RIGHTV0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDU0_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_18, WDMA_STCH_BLDV0_ENABLE, 0);
	}else {
		//bld1_rdma
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_LEFTV1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_37, RDMA_STCH_RIGHTV1_ENABLE, 0);
		//bld1_wdma
#if 0   //always close
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_LEFTV1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_39, WDMA_STCH_RIGHTV1_ENABLE, 0);
#endif
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDU1_ENABLE, 0);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_40, WDMA_STCH_BLDV1_ENABLE, 0);
	}
}
//0 = from dma data; 1 = from stitch data
void stitch_src_sel(unsigned char sel)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, SRC_SEL, SRC_SEL_LEFT0, sel);
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, SRC_SEL, SRC_SEL_RIGHT0, sel);
	//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, SRC_SEL, SRC_SEL_LEFT1, sel);//always from ddr
	//STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, SRC_SEL, SRC_SEL_RIGHT1, sel);
}

//wgt mode，0：yuv share wgt; 1: y wgt, uv share wgt; 2: y wgt, u wgt, v wgt
void stitch_mode_sel(unsigned char sel)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, MODE_SEL, MODE_SEL, sel);
}

//blending judge start and end for left&right img.
void stitch_bj_image_size_cfg(unsigned char top_id, struct stitch_bj_size_param *cfg)
{
	if (!top_id) {
		//bj0
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_2, BLD_W_STR_LEFT0, cfg->bld_w_str_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_2, BLD_W_END_LEFT0, cfg->bld_w_end_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_3, BLD_W_STR_RIGHT0, cfg->bld_w_str_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_3, BLD_W_END_RIGHT0, cfg->bld_w_end_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_13, NBLD_W_END_LEFT0, cfg->nbld_w_end_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_13, NBLD_W_END_RIGHT0, cfg->nbld_w_end_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_14, NBLD_W_STR_LEFT0, cfg->nbld_w_str_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_14, NBLD_W_STR_RIGHT0, cfg->nbld_w_str_right);
	} else {
		//bj1
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_23, BLD_W_STR_LEFT1, cfg->bld_w_str_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_23, BLD_W_END_LEFT1, cfg->bld_w_end_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_24, BLD_W_STR_RIGHT1, cfg->bld_w_str_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_24, BLD_W_END_RIGHT1, cfg->bld_w_end_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_34, NBLD_W_END_LEFT1, cfg->nbld_w_end_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_34, NBLD_W_END_RIGHT1, cfg->nbld_w_end_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_35, NBLD_W_STR_LEFT1, cfg->nbld_w_str_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_35, NBLD_W_STR_RIGHT1, cfg->nbld_w_str_right);
	}
}

//rdma chn size cfg: y/uv/wgh
//cfg[0] :y rdma channel
//cfg[1] :uv rdma channel
//cfg[2] :wgt rdma channel
void stitch_rdma_image_size_cfg(unsigned char top_id, struct stitch_rdma_size_param *cfg)
{
	if (!top_id) {
		// y rdma channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_11, IMG_HEIGHT_R_LEFTY0, cfg[0].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_11, IMG_WIDTH_R_LEFTY0, cfg[0].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_12, IMG_HEIGHT_R_RIGHTY0, cfg[0].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_12, IMG_WIDTH_R_RIGHTY0, cfg[0].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_LEFTY0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_LEFTUV0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_RIGHTY0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_RIGHTUV0, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_5, CROP_H_STR_R_LEFTY0, cfg[0].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_5, CROP_H_END_R_LEFTY0, cfg[0].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_6, CROP_H_STR_R_RIGHTY0, cfg[0].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_6, CROP_H_END_R_RIGHTY0, cfg[0].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_8, CROP_W_STR_R_LEFTY0, cfg[0].crop_w_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_8, CROP_W_END_R_LEFTY0, cfg[0].crop_w_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_9, CROP_W_STR_R_RIGHTY0, cfg[0].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_9, CROP_W_END_R_RIGHTY0, cfg[0].crop_w_end_r_right);
		//uv rdma channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_44, IMG_HEIGHT_R_LEFTUV0, cfg[1].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_44, IMG_WIDTH_R_LEFTUV0, cfg[1].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_45, IMG_HEIGHT_R_RIGHTUV0, cfg[1].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_45, IMG_WIDTH_R_RIGHTUV0, cfg[1].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_48, CROP_H_STR_R_LEFTUV0, cfg[1].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_48, CROP_H_END_R_LEFTUV0, cfg[1].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_49, CROP_H_STR_R_RIGHTUV0, cfg[1].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_49, CROP_H_END_R_RIGHTUV0, cfg[1].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_50, CROP_W_STR_R_LEFTUV0, cfg[1].crop_w_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_50, CROP_W_END_R_LEFTUV0, cfg[1].crop_w_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_51, CROP_W_STR_R_RIGHTUV0, cfg[1].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_51, CROP_W_END_R_RIGHTUV0, cfg[1].crop_w_end_r_right);
		//weight image
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_56, IMG_HEIGHT_ALPHA0, cfg[2].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_56, IMG_WIDTH_ALPHA0, cfg[2].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_57, IMG_HEIGHT_BETA0, cfg[2].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_57, IMG_WIDTH_BETA0, cfg[2].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_ALPHA0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BETA0, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_60, CROP_H_STR_ALPHA0, cfg[2].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_60, CROP_H_END_ALPHA0, cfg[2].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_61, CROP_H_STR_BETA0, cfg[2].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_61, CROP_H_END_BETA0, cfg[2].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_62, CROP_W_STR_ALPHA0, cfg[2].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_62, CROP_W_END_ALPHA0, cfg[2].crop_w_end_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_63, CROP_W_STR_BETA0, cfg[2].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_63, CROP_W_END_BETA0, cfg[2].crop_w_end_r_right);
	} else {
		// y rdma channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_32, IMG_HEIGHT_R_LEFTY1, cfg[0].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_32, IMG_WIDTH_R_LEFTY1, cfg[0].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_33, IMG_HEIGHT_R_RIGHTY1, cfg[0].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_33, IMG_WIDTH_R_RIGHTY1, cfg[0].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_LEFTY1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_LEFTUV1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_RIGHTY1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_R_RIGHTUV1, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_26, CROP_H_STR_R_LEFTY1, cfg[0].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_26, CROP_H_END_R_LEFTY1, cfg[0].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_27, CROP_H_STR_R_RIGHTY1, cfg[0].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_27, CROP_H_END_R_RIGHTY1, cfg[0].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_29, CROP_W_STR_R_LEFTY1, cfg[0].crop_w_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_29, CROP_W_END_R_LEFTY1, cfg[0].crop_w_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_30, CROP_W_STR_R_RIGHTY1, cfg[0].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_30, CROP_W_END_R_RIGHTY1, cfg[0].crop_w_end_r_right);
		//uv rdma channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_46, IMG_HEIGHT_R_LEFTUV1, cfg[1].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_46, IMG_WIDTH_R_LEFTUV1, cfg[1].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_47, IMG_HEIGHT_R_RIGHTUV1, cfg[1].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_47, IMG_WIDTH_R_RIGHTUV1, cfg[1].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_52, CROP_H_STR_R_LEFTUV1, cfg[1].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_52, CROP_H_END_R_LEFTUV1, cfg[1].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_53, CROP_H_STR_R_RIGHTUV1, cfg[1].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_53, CROP_H_END_R_RIGHTUV1, cfg[1].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_54, CROP_W_STR_R_LEFTUV1, cfg[1].crop_w_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_54, CROP_W_END_R_LEFTUV1, cfg[1].crop_w_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_55, CROP_W_STR_R_RIGHTUV1, cfg[1].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_55, CROP_W_END_R_RIGHTUV1, cfg[1].crop_w_end_r_right);
		//weight image
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_58, IMG_HEIGHT_ALPHA1, cfg[2].img_height_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_58, IMG_WIDTH_ALPHA1, cfg[2].img_width_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_59, IMG_HEIGHT_BETA1, cfg[2].img_height_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_59, IMG_WIDTH_BETA1, cfg[2].img_width_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_ALPHA1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BETA1, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_64, CROP_H_STR_ALPHA1, cfg[2].crop_h_str_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_64, CROP_H_END_ALPHA1, cfg[2].crop_h_end_r_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_65, CROP_H_STR_BETA1, cfg[2].crop_h_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_65, CROP_H_END_BETA1, cfg[2].crop_h_end_r_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_66, CROP_W_STR_ALPHA1, cfg[2].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_66, CROP_W_END_ALPHA1, cfg[2].crop_w_end_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_67, CROP_W_STR_BETA1, cfg[2].crop_w_str_r_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_67, CROP_W_END_BETA1, cfg[2].crop_w_end_r_right);
	}
}

//wdma nbld chn size cfg: y/uv
//nbld_cfg[0] :y wdma channel
//nbld_cfg[1] :uv wdma channel

//wdma bld chn size cfg: y/uv
//bld_cfg[0] :y wdma channel
//bld_cfg[1] :uv wdma channel
void stitch_wdma_image_size_cfg(unsigned char top_id, struct stitch_wdma_nbld_size_param *nbld_cfg, struct stitch_wdma_bld_size_param *bld_cfg)
{
	if (!top_id) {
		//wdma y channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_69, CROP_H_STR_W_LEFTY0, nbld_cfg[0].crop_h_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_69, CROP_H_END_W_LEFTY0, nbld_cfg[0].crop_h_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_70, CROP_H_STR_W_RIGHTY0, nbld_cfg[0].crop_h_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_70, CROP_H_END_W_RIGHTY0, nbld_cfg[0].crop_h_end_w_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_W_LEFTY0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_W_LEFTUV0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_W_RIGHTY0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_W_RIGHTUV0, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_72, CROP_W_STR_W_LEFTY0, nbld_cfg[0].crop_w_str_w_left);

		if (nbld_cfg[0].crop_w_end_w_left)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_72, CROP_W_END_W_LEFTY0, nbld_cfg[0].crop_w_end_w_left);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_72, CROP_W_END_W_LEFTY0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_73, CROP_W_STR_W_RIGHTY0, nbld_cfg[0].crop_w_str_w_right);

		if (nbld_cfg[0].crop_w_end_w_right)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_73, CROP_W_END_W_RIGHTY0, nbld_cfg[0].crop_w_end_w_right);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_73, CROP_W_END_W_RIGHTY0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_75, IMG_HEIGHT_W_LEFTY0, nbld_cfg[0].img_height_w_left);

		if (nbld_cfg[0].img_width_w_left)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_75, IMG_WIDTH_W_LEFTY0, nbld_cfg[0].img_width_w_left);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_75, IMG_WIDTH_W_LEFTY0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_76, IMG_HEIGHT_W_RIGHTY0, nbld_cfg[0].img_height_w_right);

		if (nbld_cfg[0].img_width_w_right)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_76, IMG_WIDTH_W_RIGHTY0, nbld_cfg[0].img_width_w_right);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_76, IMG_WIDTH_W_RIGHTY0, STITCH_MAGIC_SIZE);

		//wdma uv channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_80, CROP_H_STR_W_LEFTUV0, nbld_cfg[1].crop_h_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_80, CROP_H_END_W_LEFTUV0, nbld_cfg[1].crop_h_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_81, CROP_H_STR_W_RIGHTUV0, nbld_cfg[1].crop_h_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_81, CROP_H_END_W_RIGHTUV0, nbld_cfg[1].crop_h_end_w_right);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_82, CROP_W_STR_W_LEFTUV0, nbld_cfg[1].crop_w_str_w_left);

		if (nbld_cfg[1].crop_w_end_w_left)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_82, CROP_W_END_W_LEFTUV0, nbld_cfg[1].crop_w_end_w_left);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_82, CROP_W_END_W_LEFTUV0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_83, CROP_W_STR_W_RIGHTUV0, nbld_cfg[1].crop_w_str_w_right);

		if (nbld_cfg[1].crop_w_end_w_right)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_83, CROP_W_END_W_RIGHTUV0, nbld_cfg[1].crop_w_end_w_right);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_83, CROP_W_END_W_RIGHTUV0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_84, IMG_HEIGHT_W_LEFTUV0, nbld_cfg[1].img_height_w_left);

		if (nbld_cfg[1].img_width_w_left)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_84, IMG_WIDTH_W_LEFTUV0, nbld_cfg[1].img_width_w_left);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_84, IMG_WIDTH_W_LEFTUV0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_85, IMG_HEIGHT_W_RIGHTUV0, nbld_cfg[1].img_height_w_right);

		if (nbld_cfg[1].img_width_w_right)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_85, IMG_WIDTH_W_RIGHTUV0, nbld_cfg[1].img_width_w_right);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_85, IMG_WIDTH_W_RIGHTUV0, STITCH_MAGIC_SIZE);

		//bld y chnnel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_4, CROP_H_STR_BLDY0, bld_cfg[0].crop_h_str_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_4, CROP_H_END_BLDY0, bld_cfg[0].crop_h_end_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_7, CROP_W_STR_BLDY0, bld_cfg[0].crop_w_str_w_bld);

		if (bld_cfg[0].crop_w_end_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_7, CROP_W_END_BLDY0, bld_cfg[0].crop_w_end_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_7, CROP_W_END_BLDY0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BLDY0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BLDUV0, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_10, IMG_HEIGHT_BLDY0, bld_cfg[0].img_height_w_bld);

		if (bld_cfg[0].img_width_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_10, IMG_WIDTH_BLDY0, bld_cfg[0].img_width_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_10, IMG_WIDTH_BLDY0, STITCH_MAGIC_SIZE);

		//bld uv chnnel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_68, CROP_H_STR_BLDUV0, bld_cfg[1].crop_h_str_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_68, CROP_H_END_BLDUV0, bld_cfg[1].crop_h_end_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_71, CROP_W_STR_BLDUV0, bld_cfg[1].crop_w_str_w_bld);

		if (bld_cfg[1].crop_w_end_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_71, CROP_W_END_BLDUV0, bld_cfg[1].crop_w_end_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_71, CROP_W_END_BLDUV0, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_74, IMG_HEIGHT_BLDUV0, bld_cfg[1].img_height_w_bld);

		if (bld_cfg[1].img_width_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_74, IMG_WIDTH_BLDUV0, bld_cfg[1].img_width_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_74, IMG_WIDTH_BLDUV0, STITCH_MAGIC_SIZE);
	} else {
#if 0 //top1 is only bld
		//wdma y channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_69, CROP_H_STR_W_LEFTY1, nbld_cfg[0].crop_h_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_69, CROP_H_END_W_LEFTY1, nbld_cfg[0].crop_h_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_70, CROP_H_STR_W_RIGHTY1, nbld_cfg[0].crop_h_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_70, CROP_H_END_W_RIGHTY1, nbld_cfg[0].crop_h_end_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_72, CROP_W_STR_W_LEFTY1, nbld_cfg[0].crop_w_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_72, CROP_W_END_W_LEFTY1, nbld_cfg[0].crop_w_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_73, CROP_W_STR_W_RIGHTY1, nbld_cfg[0].crop_w_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_73, CROP_W_END_W_RIGHTY1, nbld_cfg[0].crop_w_end_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_75, IMG_HEIGHT_W_LEFTY1, nbld_cfg[0].img_height_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_75, IMG_WIDTH_W_LEFTY1, nbld_cfg[0].img_width_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_76, IMG_HEIGHT_W_RIGHTY1, nbld_cfg[0].img_height_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_76, IMG_WIDTH_W_RIGHTY1, nbld_cfg[0].img_width_w_right);
		//wdma uv channel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_80, CROP_H_STR_W_LEFTUV1, nbld_cfg[1].crop_h_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_80, CROP_H_END_W_LEFTUV1, nbld_cfg[1].crop_h_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_81, CROP_H_STR_W_RIGHTUV1, nbld_cfg[1].crop_h_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_81, CROP_H_END_W_RIGHTUV1, nbld_cfg[1].crop_h_end_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_82, CROP_W_STR_W_LEFTUV1, nbld_cfg[1].crop_w_str_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_82, CROP_W_END_W_LEFTUV1, nbld_cfg[1].crop_w_end_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_83, CROP_W_STR_W_RIGHTUV1, nbld_cfg[1].crop_w_str_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_83, CROP_W_END_W_RIGHTUV1, nbld_cfg[1].crop_w_end_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_84, IMG_HEIGHT_W_LEFTUV1, nbld_cfg[1].img_height_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_84, IMG_WIDTH_W_LEFTUV1, nbld_cfg[1].img_width_w_left);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_85, IMG_HEIGHT_W_RIGHTUV1, nbld_cfg[1].img_height_w_right);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_85, IMG_WIDTH_W_RIGHTUV1, nbld_cfg[1].img_width_w_right);
#endif
		//bld y chnnel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_25, CROP_H_STR_BLDY1, bld_cfg[0].crop_h_str_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_25, CROP_H_END_BLDY1, bld_cfg[0].crop_h_end_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_28, CROP_W_STR_BLDY1, bld_cfg[0].crop_w_str_w_bld);

		if (bld_cfg[0].crop_w_end_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_28, CROP_W_END_BLDY1, bld_cfg[0].crop_w_end_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_28, CROP_W_END_BLDY1, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BLDY1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP_ENABLE_BLDUV1, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_31, IMG_HEIGHT_BLDY1, bld_cfg[0].img_height_w_bld);

		if (bld_cfg[0].img_width_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_31, IMG_WIDTH_BLDY1, bld_cfg[0].img_width_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_31, IMG_WIDTH_BLDY1, STITCH_MAGIC_SIZE);

		//bld uv chnnel
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_77, CROP_H_STR_BLDUV1, bld_cfg[1].crop_h_str_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_77, CROP_H_END_BLDUV1, bld_cfg[1].crop_h_end_w_bld);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_78, CROP_W_STR_BLDUV1, bld_cfg[1].crop_w_str_w_bld);

		if (bld_cfg[1].crop_w_end_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_78, CROP_W_END_BLDUV1, bld_cfg[1].crop_w_end_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_78, CROP_W_END_BLDUV1, STITCH_MAGIC_SIZE);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_79, IMG_HEIGHT_BLDUV1, bld_cfg[1].img_height_w_bld);

		if (bld_cfg[1].img_width_w_bld)
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_79, IMG_WIDTH_BLDUV1, bld_cfg[1].img_width_w_bld);
		else
			STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_79, IMG_WIDTH_BLDUV1, STITCH_MAGIC_SIZE);
	}
}

//crop src img send to blending judge, left img drop right part, right img drop left part.
void stitch_crop2bj_cfg(unsigned char top_id, struct stitch_crop2bj_param *cfg)
{
	if (!top_id) {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP2BJ_LEFT_ENABLE0, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP2BJ_RIGHT_ENABLE0, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_87, CROP2BJ_LEFT_IMG_HEIGHT0, cfg->left_img_height);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_87, CROP2BJ_LEFT_IMG_WIDTH0, cfg->left_img_width);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_88, CROP2BJ_RIGHT_IMG_HEIGHT0, cfg->right_img_height);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_88, CROP2BJ_RIGHT_IMG_WIDTH0, cfg->right_img_width);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_89, CROP2BJ_LEFT_CROP_H_STR0, cfg->left_crop_h_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_89, CROP2BJ_LEFT_CROP_H_END0, cfg->left_crop_h_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_90, CROP2BJ_RIGHT_CROP_H_STR0, cfg->right_crop_h_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_90, CROP2BJ_RIGHT_CROP_H_END0, cfg->right_crop_h_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_91, CROP2BJ_LEFT_CROP_W_STR0, cfg->left_crop_w_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_91, CROP2BJ_LEFT_CROP_W_END0, cfg->left_crop_w_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_92, CROP2BJ_RIGHT_CROP_W_STR0, cfg->right_crop_w_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_92, CROP2BJ_RIGHT_CROP_W_END0, cfg->right_crop_w_end);
	} else {
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP2BJ_LEFT_ENABLE1, 1);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_86, CROP2BJ_RIGHT_ENABLE1, 1);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_93, CROP2BJ_LEFT_IMG_HEIGHT1, cfg->left_img_height);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_93, CROP2BJ_LEFT_IMG_WIDTH1, cfg->left_img_width);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_94, CROP2BJ_RIGHT_IMG_HEIGHT1, cfg->right_img_height);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_94, CROP2BJ_RIGHT_IMG_WIDTH1, cfg->right_img_width);

		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_95, CROP2BJ_LEFT_CROP_H_STR1, cfg->left_crop_h_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_95, CROP2BJ_LEFT_CROP_H_END1, cfg->left_crop_h_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_96, CROP2BJ_RIGHT_CROP_H_STR1, cfg->right_crop_h_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_96, CROP2BJ_RIGHT_CROP_H_END1, cfg->right_crop_h_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_97, CROP2BJ_LEFT_CROP_W_STR1, cfg->left_crop_w_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_97, CROP2BJ_LEFT_CROP_W_END1, cfg->left_crop_w_end);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_98, CROP2BJ_RIGHT_CROP_W_STR1, cfg->right_crop_w_str);
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_98, CROP2BJ_RIGHT_CROP_W_END1, cfg->right_crop_w_end);
	}
}

static void stitch_dma_model_sel(enum stitch_dma_id dma_id)
{
	//dma model select fix to sw mode
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, SYS_CONTROL, BASE_SEL, 1);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, SYS_CONTROL, STRIDE_SEL, 1);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, SYS_CONTROL, SEGLEN_SEL, 1);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, SYS_CONTROL, SEGNUM_SEL, 1);
}

//cfg dma register, total 28 chn
void stitch_dma_cfg(struct stitch_dma_ctl *cfg)
{
	enum stitch_dma_id dma_id = cfg->dma_id;

	stitch_dma_model_sel(dma_id);

	if (gStitchDumpDmaCfg)
		TRACE_STITCH(DBG_DEBUG, "stitch_dma_ctl_addr-dma_id-addr-w-stride-h[%#lx-%d-%#llx-%d-%d-%d]\n"
			, stitch_dma[dma_id],  dma_id, cfg->addr, cfg->width, cfg->stride, cfg->height);

	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, BASE_ADDR,   BASEL,  cfg->addr & 0xffffffff);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, SYS_CONTROL, BASEH,  (cfg->addr >> 32));
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, DMA_SEGLEN,  SEGLEN, cfg->width);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, DMA_STRIDE,  STRIDE, cfg->stride);
	STITCH_WR_BITS(stitch_dma[dma_id], REG_STITCH_DMA_CTL_T, DMA_SEGNUM,  SEGNUM, cfg->height);
}

void stitch_dma_cfg_clr_all(void)
{
	unsigned char i = 0;
	struct stitch_dma_ctl cfg;

	for (i = 0; i < ID_DMA_STCH_MAX; i++) {
		memset(&cfg, 0, sizeof(cfg));
		cfg.dma_id = (enum stitch_dma_id)i;
		stitch_dma_cfg(&cfg);
	}
}

void stitch_intr_clr(void)
{
	STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, INTERRUPT_CLR_W1P, 1);
}

//read intr status,0x3:stitch success, 0x0:fail
unsigned char stitch_intr_status(void)
{
	unsigned char status = 0;

	status |= STITCH_RD_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_0, FRAME_DONE);
	status |= STITCH_RD_BITS(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL, STITCH_INTER_FLOW) << 1;

	return status;
}

//alpha_pixel + beta_pixel = 8’d255
//blend_out = (alpha_pixel*(left_pixel<<8) + beta_pixel*(right_pixel<<8))>>reg_x
void stitch_set_regx(unsigned char top_id, unsigned char regx)
{
	if (!top_id)
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_19, X_0, regx);
	else
		STITCH_WR_BITS(reg_base, REG_STITCHING_BLENDING_T, REG_41, X_1, regx);
}

void stitch_dump_register(void)
{
	unsigned char i;

	if (gStitchDumpReg) {
		TRACE_STITCH(DBG_NOTICE, "stitch REG_0=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_0));
		TRACE_STITCH(DBG_NOTICE, "stitch FLOW_CONTROL=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, FLOW_CONTROL));
		TRACE_STITCH(DBG_NOTICE, "stitch STCH_SHDW_SEL=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, STCH_SHDW_SEL));
		TRACE_STITCH(DBG_NOTICE, "stitch MODE_SEL=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, MODE_SEL));
		TRACE_STITCH(DBG_NOTICE, "stitch SRC_SEL=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, SRC_SEL));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_1=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_1));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_2=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_2));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_3=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_3));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_4=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_4));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_5=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_5));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_6=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_6));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_7=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_7));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_8=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_8));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_9=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_9));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_10=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_10));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_11=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_11));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_12=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_12));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_13=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_13));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_14=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_14));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_15=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_15));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_16=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_16));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_17=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_17));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_18=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_18));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_19=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_19));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_20=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_20));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_21=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_21));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_22=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_22));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_23=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_23));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_24=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_24));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_25=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_25));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_26=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_26));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_27=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_27));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_28=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_28));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_29=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_29));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_30=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_30));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_31=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_31));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_32=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_32));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_33=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_33));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_34=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_34));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_35=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_35));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_36=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_36));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_37=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_37));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_38=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_38));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_39=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_39));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_40=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_40));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_41=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_41));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_42=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_42));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_43=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_43));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_44=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_44));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_45=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_45));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_46=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_46));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_47=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_47));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_48=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_48));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_49=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_49));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_50=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_50));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_51=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_51));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_52=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_52));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_53=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_53));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_54=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_54));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_55=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_55));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_56=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_56));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_57=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_57));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_58=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_58));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_59=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_59));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_60=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_60));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_61=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_61));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_62=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_62));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_63=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_63));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_64=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_64));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_65=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_65));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_66=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_66));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_67=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_67));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_68=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_68));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_69=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_69));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_70=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_70));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_71=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_71));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_72=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_72));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_73=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_73));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_74=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_74));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_75=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_75));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_76=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_76));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_77=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_77));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_78=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_78));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_79=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_79));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_80=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_80));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_81=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_81));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_82=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_82));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_83=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_83));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_84=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_84));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_85=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_85));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_86=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_86));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_87=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_87));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_88=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_88));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_89=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_89));

		TRACE_STITCH(DBG_NOTICE, "stitch REG_90=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_90));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_91=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_91));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_92=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_92));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_93=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_93));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_94=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_94));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_95=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_95));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_96=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_96));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_97=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_97));
		TRACE_STITCH(DBG_NOTICE, "stitch REG_98=0x%08x\n", STITCH_RD_REG(reg_base, REG_STITCHING_BLENDING_T, REG_98));

		for (i = 0; i < STITCH_DMA_REG_NUM; i++) {
			TRACE_STITCH(DBG_NOTICE, "----------------stitch DMAID[%d]--------------------\n", i);
			TRACE_STITCH(DBG_NOTICE, "stitch SYS_CONTROL=0x%08x\n", STITCH_RD_REG(stitch_dma[i], REG_STITCH_DMA_CTL_T, SYS_CONTROL));
			TRACE_STITCH(DBG_NOTICE, "stitch BASE_ADDR=0x%08x\n", STITCH_RD_REG(stitch_dma[i], REG_STITCH_DMA_CTL_T, BASE_ADDR));
			TRACE_STITCH(DBG_NOTICE, "stitch DMA_SEGLEN=0x%08x\n", STITCH_RD_REG(stitch_dma[i], REG_STITCH_DMA_CTL_T, DMA_SEGLEN));
			TRACE_STITCH(DBG_NOTICE, "stitch DMA_STRIDE=0x%08x\n", STITCH_RD_REG(stitch_dma[i], REG_STITCH_DMA_CTL_T, DMA_STRIDE));
			TRACE_STITCH(DBG_NOTICE, "stitch DMA_SEGNUM=0x%08x\n", STITCH_RD_REG(stitch_dma[i], REG_STITCH_DMA_CTL_T, DMA_SEGNUM));
		}
	}
}

